#Toggle whether Elite Raiders will spawn in Raids or not. On Hero, Elites will not spawn regardless of this, and on Legend, only Tier 1 elites will spawn if enabled.
elitesEnabled = true
#Determines the chance that Reinforcements will spawn on any wave of a Raid.
#Range: 0 ~ 100
reinforcementChance = 40
#Determines the chance that an individual Raider will be wearing some armor during a Raid.
#Range: 0 ~ 100
armorChance = 40
#Determines the maximum pieces of armor Raiders can have equipped.
#Range: 0 ~ 4
maxArmorPieces = 1
#Valid tiers of armor that Raiders can have equipped during Raids. Valid values: LEATHER, CHAIN, IRON, DIAMOND, NETHERITE (Case-Sensitive!).
validArmorTiers = ["IRON", "DIAMOND", "NETHERITE"]
#Determines the chance that Raider armor will be enchanted with Protection.
#Range: 0 ~ 100
protectionChance = 15
#The maximum level of Protection that any Raider's armor will be enchanted with.
#Range: 0 ~ 10
minProtectionLevel = 3
#The minimum level of Protection that any Raider's armor will be enchanted with.
#Range: 0 ~ 10
maxProtectionLevel = 4

#Change settings regarding the Assassin Illager Entity during Raids.
["Assassin Illager"]
	#Determines the level of Sharpness that Assassin Illager Swords will be enchanted with.
	#Range: 0 ~ 10
	assassinSharpnessLevel = 2

#Change settings regarding the Dart Illager Entity during Raids.
["Dart Illager"]
	#Determines the level of Sharpness that Dart Illager Swords will be enchanted with.
	#Range: 0 ~ 10
	dartSharpnessLevel = 4

#Change settings regarding the Electro Illager Entity during Raids.
["Electro Illager"]
	#The damage that the Electro Illager's Concentrated Bolt spell deals.
	#Range: 0.1 ~ 1.7976931348623157E308
	electroConcentratedBoltDamage = 24.0
	#Determines the number of lightning strikes generated by the Electro Illager's Generic Lightning attack.
	#Range: > 1
	electroGenericLightningStrikeCount = 8
	#If true, Electro Illagers will summon a second set of Lightning Bolts during their Ring Lightning attack.
	electroExtraRingBolts = true

#Change settings regarding the Frost Illager Entity during Raids.
["Frost Illager"]
	#Determines the damage of individual snowballs in the Frost Illager's Snowball Blast attack
	#Range: 0.1 ~ 1.7976931348623157E308
	frostSnowballBlastDamage = 7.0
	#Determines the duration of the Frost Illager's Barrage attack, in ticks (20 ticks = 1 second).
	#Range: > 1
	frostBarrageDuration = 300
	#Determines the duration of the Frost Illager's Freeze attack, in ticks (20 ticks = 1 second). Mining Fatigue duration will be 1/4 of this value.
	#Range: > 1
	frostFreezeDuration = 200

#Change settings regarding the Necromancer Illager Entity during Raids.
["Necromancer Illager"]
	#The number of mobs spawned when the Necromancer uses its Summon Minions attack.
	#Range: > 0
	necromancerMinionSummonCount = 5
	#The maximum level of Protection a Summoned Minion's armor will be enchanted with. The actual level of Protection will randomly chosen between 1 and this value. 0 removes this enchantment from Minion armor.
	#Range: 0 ~ 10
	minionProtectionLevel = 3
	#The number of mobs spawned when the Necromancer uses its Summon Horde attack.
	#Range: > 0
	necromancerHordeSize = 20
	#How long Necromancer Summoned Hordes will be alive before dying automatically, in ticks (20 ticks = 1 second).
	#Range: > 0
	necromancerHordeLifetime = 1800

#Change settings regarding the Shaman Illager Entity during Raids.
["Shaman Illager"]
	#The amount of debuffs the Shaman will inflict during its primary attack.
	#Range: 0 ~ 6
	shamanDebuffAmount = 4
	#Duration of the Nausea Effect inflicted by the Shaman, in ticks (20 ticks = 1 second).
	#Range: > 0
	shamanNauseaDuration = 80
	#Duration of the Slowness Effect inflicted by the Shaman, in ticks (20 ticks = 1 second).
	#Range: > 0
	shamanSlownessDuration = 160
	#Amplifier of the Slowness Effect inflicted by the Shaman, in ticks (20 ticks = 1 second).
	#Range: > 0
	shamanSlownessAmplifier = 2
	#Duration of the Mining Fatigue Effect inflicted by the Shaman, in ticks (20 ticks = 1 second).
	#Range: > 0
	shamanMiningFatigueDuration = 160
	#Amplifier of the Mining Fatigue Effect inflicted by the Shaman, in ticks (20 ticks = 1 second).
	#Range: > 0
	shamanMiningFatigueAmplifier = 2
	#Duration of the Poison Effect inflicted by the Shaman, in ticks (20 ticks = 1 second).
	#Range: > 0
	shamanPoisonDuration = 100
	#Amplifier of the Poison Effect inflicted by the Shaman, in ticks (20 ticks = 1 second).
	#Range: > 0
	shamanPoisonAmplifier = 4
	#Duration of the Levitation Effect inflicted by the Shaman, in ticks (20 ticks = 1 second).
	#Range: > 0
	shamanLevitationDuration = 100
	#Weakness of the Weakness Effect inflicted by the Shaman, in ticks (20 ticks = 1 second).
	#Range: > 0
	shamanWeaknessDuration = 120
	#Amplifier of the Weakness Effect inflicted by the Shaman, in ticks (20 ticks = 1 second).
	#Range: > 0
	shamanWeaknessAmplifier = 3
	#The maximum radius of the Shaman's boost attacks. All raiders within this radius of the Shaman will receive boosts.
	#Range: 0.0 ~ 1.7976931348623157E308
	shamanBuffRadius = 12.0
	#The duration of the Resistance Effect that the Shaman gives its allies.
	#Range: > 0
	shamanAllyResistanceDuration = 160
	#The amplifier of the Resistance Effect that the Shaman gives its allies.
	#Range: > 0
	shamanAllyResistanceAmplifier = 2
	#The duration of the Strength Effect that the Shaman gives its allies.
	#Range: > 0
	shamanAllyStrengthDuration = 200
	#The amplifier of the Strength Effect that the Shaman gives its allies.
	#Range: > 0
	shamanAllyStrengthAmplifier = 2

#Change settings regarding the Tank Illager Entity during Raids.
["Tank Illager"]
	#Determines the level of Protection that Tank Illager armor will be enchanted with. 0 to disable.
	#Range: 0 ~ 10
	tankProtectionLevel = 4
	#Determines the level of Thorns that Tank Illager armor will be enchanted with. 0 to disable.
	#Range: 0 ~ 10
	tankThornsLevel = 2

#Change settings regarding the Warrior Illager Entity during Raids.
["Warrior Illager"]
	#Determines the possible swords that Warrior Illagers can have equipped during Raids. Valid Swords: STONE, GOLD, IRON, DIAMOND, NETHERITE (Case-Sensitive!).
	warriorPossibleSwords = ["IRON", "DIAMOND", "NETHERITE"]
	#Determines the chance that Warrior Illager swords will be enchanted with some level of Sharpness.
	#Range: 0 ~ 100
	warriorSharpnessChance = 45
	#The minimum level of Sharpness that Warrior Illager swords will be enchanted with.
	#Range: 1 ~ 10
	warriorMinSharpnessLevel = 3
	#The maximum level of Sharpness that Warrior Illager swords will be enchanted with.
	#Range: 1 ~ 10
	warriorMaxSharpnessLevel = 5
	#Determines the chance that Warrior Illager swords will be enchanted with some level of Fire Aspect.
	#Range: 0 ~ 100
	warriorFireAspectChance = 15
	#The level of Fire Aspect that Warrior Illager swords will be enchanted with.
	#Range: 1 ~ 10
	warriorFireAspectLevel = 2
	#Determines the chance that Warrior Illager swords will be enchanted with some level of Knockback.
	#Range: 0 ~ 100
	warriorKnockbackChance = 20
	#The level of Knockback that Warrior Illager swords will be enchanted with.
	#Range: 1 ~ 10
	warriorKnockbackLevel = 2

