
[Illagers]
	#Determines if Vindicators will show up in Raids.
	enableVindicators = true
	#Determines if Evokers will show up in Raids.
	enableEvokers = true
	#Determines if Pillagers will show up in Raids.
	enablePillagers = true
	#Determines if Witches will show up in Raids.
	enableWitches = true
	#Determines if Ravagers will show up in Raids.
	enableRavagers = true
	#Determines if Illusioners will show up in Raids.
	enableIllusioners = true
	#Determines if Warriors will show up in Raids.
	enableWarriors = true
	#Determines if Darts will show up in Raids.
	enableDarts = true
	#Determines if Conductors will show up in Raids.
	enableConductors = true
	#Determines if Necromancers will show up in Raids.
	enableNecromancers = true
	#Determines if Shamans will show up in Raids.
	enableShamans = true
	#Determines if Tanks will show up in Raids.
	enableTanks = true
	#Determines if Assassins will show up in Raids.
	enableAssassins = true
	#Determines if Frostmages will show up in Raids.
	enableFrostmages = true
	#(IF HunterIllager IS INSTALLED) Determines if Hunters will show up in Raids.
	enableHunters = true
	#(IF EnchantWithMob IS INSTALLED) Determines if Enchanters will show up in Raids.
	enableEnchanters = true

