
["Explosive Arrow"]
	#Adjust this to set the damage for the Explosive Arrow. Vanilla Arrow value is 2.0.
	#Range: 0.0 ~ 16.0
	Damage = 0.5
	#Adjust this to set the explosion strength for the Explosive Arrow.
	#Range: 0.5 ~ 16.0
	Strength = 1.9
	#If TRUE, explosions break blocks.
	"Break Blocks" = true
	#If TRUE, explosions cause fires if the arrow is on fire.
	"Cause Fires" = true
	#If TRUE, bounces are modified by knockback bonuses, such as the Punch Enchantment.
	"Knockback Boost" = true

["Quartz Arrow"]
	#Adjust this to set the damage for the Quartz Arrow. Vanilla Arrow value is 2.0.
	#Range: 0.0 ~ 16.0
	Damage = 2.5
	#Adjust this to set the inherent knockback strength of the Quartz Arrow. Vanilla Arrow value is 0.
	#Range: 0 ~ 16
	Knockback = 1
	#Adjust this to set the inherent pierce of the Quartz Arrow. Vanilla Arrow value is 0.
	#Range: 0 ~ 16
	Piercing = 0

["Diamond Arrow"]
	#Adjust this to set the damage for the Diamond Arrow. Vanilla Arrow value is 2.0.
	#Range: 0.0 ~ 16.0
	Damage = 4.0
	#Adjust this to set the inherent knockback strength of the Diamond Arrow. Vanilla Arrow value is 0.
	#Range: 0 ~ 16
	Knockback = 0
	#Adjust this to set the inherent pierce of the Diamond Arrow. Vanilla Arrow value is 0.
	#Range: 0 ~ 16
	Piercing = 1

["Prismarine Arrow"]
	#Adjust this to set the damage for the Prismarine Arrow. Vanilla Arrow value is 2.0.
	#Range: 0.0 ~ 16.0
	Damage = 2.0
	#Adjust this to set the inherent knockback strength of the Prismarine Arrow. Vanilla Arrow value is 0.
	#Range: 0 ~ 16
	Knockback = 0
	#Adjust this to set the inherent pierce of the Prismarine Arrow. Vanilla Arrow value is 0.
	#Range: 0 ~ 16
	Piercing = 0

["Slime Arrow"]
	#Adjust this to set the damage for the Slime Arrow. Vanilla Arrow value is 2.0.
	#Range: 0.0 ~ 16.0
	Damage = 0.5
	#Adjust this to set the inherent knockback strength of the Slime Arrow. Vanilla Arrow value is 0.
	#Range: 0 ~ 16
	Knockback = 4
	#Adjust this to set the number of bounces for the Slime Arrow.
	#Range: 1 ~ 16
	Bounces = 4
	#If TRUE, bounces are modified by knockback bonuses, such as the Punch Enchantment.
	"Knockback Boost" = true

["Shulker Arrow"]
	#Adjust this to set the damage for the Shulker Arrow. Vanilla Arrow value is 2.0.
	#Range: 0.0 ~ 16.0
	Damage = 2.5
	#Adjust this to set the effect duration (Levitation) for the Shulker Arrow. (In ticks; there are 20 ticks per second).
	#Range: 20 ~ 1200
	"Effect Duration" = 100

["Blaze Arrow"]
	#Adjust this to set the damage for the Blaze Arrow. Vanilla Arrow value is 2.0.
	#Range: 0.0 ~ 16.0
	Damage = 1.5
	#Adjust this to set the burn duration for the Blaze Arrow (in seconds). Nearby targets will burn for 5 seconds less than a direct target.
	#Range: 5 ~ 30
	"Burn Duration" = 10
	#Adjust this to set the effect radius for the Blaze Arrow. Set to 0 to disable, but that would be boring.
	#Range: 0 ~ 16
	Radius = 2

["Frost Arrow"]
	#Adjust this to set the damage for the Frost Arrow. Vanilla Arrow value is 2.0.
	#Range: 0.0 ~ 16.0
	Damage = 1.5
	#Adjust this to set the chill duration for the Frost Arrow. (In ticks; there are 20 ticks per second).
	#Range: 20 ~ 1200
	"Chill Duration" = 100
	#Adjust this to set the effect radius for the Frost Arrow. Set to 0 to disable, but that would be boring.
	#Range: 0 ~ 16
	Radius = 4
	#If TRUE, Frost Arrows will convert Lava into Obsidian. If FALSE, Glossed Magma.
	"Permanent Lava Freeze" = true
	#If TRUE, Frost Arrows will convert Water into Ice. If FALSE, Frosted Ice.
	"Permanent Water Freeze" = true

["Verdant Arrow"]
	#Adjust this to set the damage for the Verdant Arrow. Vanilla Arrow value is 2.0.
	#Range: 0.0 ~ 16.0
	Damage = 0.5
	#Adjust this to set the effect radius for the Verdant Arrow. Set to 0 to disable, but that would be boring.
	#Range: 0 ~ 16
	Radius = 4

["Spore Arrow"]
	#Adjust this to set the damage for the Spore Arrow. Vanilla Arrow value is 2.0.
	#Range: 0.0 ~ 16.0
	Damage = 0.5
	#Adjust this to set the effect radius for the Spore Arrow. Set to 0 to disable, but that would be boring.
	#Range: 0 ~ 16
	Radius = 4

