
#List of affix configurations
[[affixes]]
	identifier = "adaptable"
	enabled = true
	minTier = 3
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "arctic"
	enabled = true
	minTier = 1
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "dampening"
	enabled = true
	minTier = 1
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "desecrating"
	enabled = true
	minTier = 4
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "enkindling"
	enabled = true
	minTier = 1
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "hasty"
	enabled = true
	minTier = 2
	maxTier = 5
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "infested"
	enabled = true
	minTier = 2
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "knocking"
	enabled = true
	minTier = 1
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "lively"
	enabled = true
	minTier = 1
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "magnetic"
	enabled = false
	minTier = 1
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "molten"
	enabled = true
	minTier = 1
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "paralyzing"
	enabled = true
	minTier = 2
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "plagued"
	enabled = false
	minTier = 2
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "reflective"
	enabled = true
	minTier = 4
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "shielding"
	enabled = false
	minTier = 1
	mobList = []
	mobPermission = "BLACKLIST"

[[affixes]]
	identifier = "wounding"
	enabled = true
	minTier = 1
	mobList = []
	mobPermission = "BLACKLIST"

