
#List of curio slot type settings
[[curiosSettings]]
	identifier = "artifact"
	size = 3
[[curiosSettings]]
	identifier = "head"
	size = 1
[[curiosSettings]]
	identifier = "necklace"
	size = 2
[[curiosSettings]]
	identifier = "back"
	size = 1
[[curiosSettings]]
	identifier = "an_focus"
	size = 1
[[curiosSettings]]
	identifier = "body"
	size = 1
[[curiosSettings]]
	identifier = "emblem"
	size = 1
	icon = "curios:slot/empty_emblem_slot"
[[curiosSettings]]
	identifier = "magic_book"
	size = 1
[[curiosSettings]]
	identifier = "medal"
	size = 1	
[[curiosSettings]]
	identifier = "scroll"
	size = 1
[[curiosSettings]]
	identifier = "spellstone"
	size = 1
[[curiosSettings]]
	identifier = "bracelet"
	size = 1
[[curiosSettings]]
	identifier = "hands"
	size = 2
[[curiosSettings]]
	identifier = "curse_ring"
	size = 1
	icon = "curios:slot/cursed_ring_slot"
[[curiosSettings]]
	identifier = "ring"
	size = 2
[[curiosSettings]]
	identifier = "belt"
	size = 1
[[curiosSettings]]
	identifier = "charm"
	size = 2
[[curiosSettings]]
	identifier = "feet"
	size = 1
[[curiosSettings]]
	identifier = "pocket"
	size = 1