
["Dog Constants"]
	#Disable hunger mode for the dog
	disable_hunger = false
	#When enabled you will spawn with a guide, Doggy Charm and Command Emblem.
	enable_starting_items = false
	#When enabled, dogs will be randomly assigned genders and will only mate and produce children with the opposite gender.
	enable_gender = true
	#When enabled, puppies get some levels from parents. When disabled, puppies start at 0 points.
	enable_pup_get_parent_levels = false

