"Allow all items to be added" = false
"Whitelisted Items" = ["alexsmobs:animal_dictionary", "ars_nouveau:worn_notebook", "betterendforge:guidebook", "patchouli:guide_book", "cookingforblockheads:recipe_book", "eidolon:codex", "iceandfire:bestiary", "mushroomquest:mycopedia", "mysticalworld:encyclopedia", "solpotato:food_book"]
"Whitelisted Names" = []
"Blacklisted Mods" = []
"Mod Aliases" = []

