
[general]
	disable_mod = false
	space_modules = true
	shadow_text = true
	animations = false
	animationSpeed = 1.0
	background_color = 1867534416

[[modules_left]]
	name = "minecraft"
	name_color = 10506797
	value_color = 43520
	enabled = true

	[modules_left.lines]
		minecraft = true

[[modules_left]]
	name = "fps"
	color_high = 5635925
	color_med = 16777045
	color_low = 16733525
	enabled = true

	[modules_left.lines]
		fps = true

[[modules_left]]
	name = "graphics"
	name_color = 16755200
	value_color = 5636095
	enabled = false

	[modules_left.lines]
		render_distance = true
		graphics = true
		clouds = true
		biome_blend_radius = true
		shader = true

[[modules_left]]
	name = "server"
	name_color = 11184810
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		server_tick = true
		packets_sent = true
		packets_received = true

[[modules_left]]
	name = "coords"
	name_color = 16733525
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	enabled = true

	[modules_left.lines]
		player_coords = true
		block_coords = false
		chunk_relative_coords = false
		chunk_coords = false

[[modules_left]]
	name = "chunks"
	name_color = 43775
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		chunk_sections = true
		chunk_culling = true
		pending_chunks = true
		pending_uploads = true
		available_buffers = false
		client_chunk_cache = false
		loaded_chunks = true
		loaded_chunks_server = true
		forceloaded_chunks = true
		spawn_chunks = true

[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		dimension = true
		facing = true
		rotation = false
		light = true
		light_server = true
		highest_block = false
		highest_block_server = false
		biome = true
		local_difficulty = false
		days_played = true

[[modules_left]]
	name = "entity"
	name_color = 16733525
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		particles = true
		entities = true
		monster = true
		creature = true
		ambient = true
		water_creature = true
		water_ambient = true
		misc = true
		ie_creature = true
		pvj_ambient = true
		pvj_water_ambient = true
		pvj_night_ambient = true
		"endergetic:end_creature" = true

[[modules_left]]
	name = "sound"
	name_color = 16755200
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		sounds = true
		ambient_sounds = true

[[modules_left]]
	name = "help"
	name_color = 16645526
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		pie_graph = true
		fps_tps = true
		help = true

[[modules_left]]
	name = "empty"
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "miscleft"
	name_color = 16645526
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		misc_left = true

[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	enabled = true

	[modules_right.lines]
		java_version = true
		memory_usage = true
		allocated_memory = true
		cpu = true
		display = false
		gpu = true
		opengl_version = false
		gpu_driver = true

[[modules_right]]
	name = "miscright"
	name_color = 16645526
	value_color = 5636095
	enabled = false

	[modules_right.lines]
		misc_right = true

[[modules_right]]
	name = "empty"
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "target"
	name_color = 43775
	value_color = 16777045
	enabled = false

	[modules_right.lines]
		targeted_block = true
		id_block = true
		block_states = true
		block_tags = true
		nothing = true
		targeted_fluid = true
		id_fluid = true
		fluid_states = true
		fluid_tags = true
		nothing2 = true
		targeted_entity = true

