#The title to display at the top of the entry.
title = "Need a server?"
#The description to display below the title.
description = "Click me to get your own server!"
#Your partner ID to use in during the ordering process.
#Without this you will not be credited for the purchases.
#(Your partner id is not the same as your referral link, please check your client area to find your partner id at https://www.bisecthosting.com/partners/console.php).
partnerId = ""
#The id of this modpack.
#(This is BH internal pack id; Find the id here: https://www.bisecthosting.com/partners/console.php)
pack_id = ""
#Set this to true to use specific language translation keys.
#This requires a custom mod that adds resource files, such as OpenLoader.
#Use 'server_entry.title' key for the Title;
#Use 'server_entry.description' key for the Description.
use_language_files = false

