#Add owner name to some messages
AddOwner = true
#Mob explosions can destroy blocks based on mob target
MobDestroy = true
#Explosions caused by any player can destroy blocks
PvpMode = false
#Report placing fluid from a bucket
ReportBucket = false
#Chunks from world spawn
#Range: -1 ~ 5000
ChunksFromSpawn = 10
#Maximum claims per player
#Range: 0 ~ 250
ClaimLimit = 4
#Blocks that bypass claims on right click
BypassBlocks = ["minecraft:ender_chest", "minecraft:smithing_table", "lootr:*-lootr", "tombstone:*-grave", "minecraft:crafting_table", "blue_skies:food_prep_table", "blue_skies:tool_box", "minecraft:bell", "minecraft:grindstone", "twilightforest:*-trophy", "minecraft:fletching_table", "minecraft:cartography_table", "blue_skies:summoning_table", "blue_skies:alchemy_table", "minecraft:stonecutter", "minecraft:loom", "waystones:*-way"]
#Entities that bypass claims on right click
BypassEntities = ["goblintraders:goblin_trader", "minecraft:wandering_trader", "rats:plague_doctor"]
#Include dimensions
IncludeDims = ["*"]
#Exclude dimensions
ExcludeDims = [""]

