
#Christmas Festivity Configurations
[christmasfestivity]
	#This set if the mod generate the gift inside the Present on the Christmas day. Set to 'false' for disable it.
	christmas_gift = true
	#This make the game send a chat message on the Christmas day. Set to 'false' for disable it.
	christmas_message = true
	#This disable the spawn of particle on the Toppers blocks. Set to 'false' for disable it.
	toppers_particles = true
	#This disable the function of right click the item to get a reward. Set to 'false' for disable it.
	advent_calendar = true

