
["Feature Options"]

	["Feature Options".EndStructures]
		#
		# Whether or not to spawn Shulker Factories - End City inspired structures with a shulker spawner
		# Default value is true
		shulkerFactorys = true
		#
		# How often Shulker Factories will attempt to spawn per chunk. 
		# It will spawn in a chunk if a random number between 0 and 1 is less than 1/(((spawnRate + spawnRate * 0.75) / 2, 2)^2)
		# This is to keep it consistent with older versions which went off of the separation instead of being truly random.
		# 10 to practically always have one in render distance, 1000 for extremely rare factories
		# 20 is slightly more common than end cities
		# Default value of 200 should average one every ~7,000 blocks (varies widely)
		#Range: 10 ~ 1000
		shulkerFactorySpawnrate = 200
		#
		# Whether or not to add a map, similar to the ones which cartographers sell, to the loot table for
		# End City Chests (and by extention very rarely within shulker factory chests)
		# Default value is true
		addMapsToShulkerFactoriesToEndCities = true
		#
		# The chance of getting a map to a Shulker Factory from a chest in an End Citythe probability of getting the map in any given chest is 1/shulkerFactoryMapWeight
		#Range: 1 ~ 1000
		shulkerFactoryMapChance = 5

	["Feature Options".Farmability]
		#
		# Whether or not bonemeal can spawn oak saplings
		# Default value is true
		bonemealCanSpawnSapling = true
		#
		# Chance of attempting to spawn an oak sapling on a random block in a 7x3x7 area centered on the bonemealed block when bonemealing grass.
		# The probability of attempting to spawn an oak sapling each time gass is bonemealed is 1/spawnrate.
		# The probability of a sapling appearing is 1 - (((1 - ((plantableBlocksInRadius/147) * 1/bonemealSaplingSpawnRate))) ^ bonemealSaplingSpawnAttempts)
		# Default value is 6
		#Range: 1 ~ 1000
		bonemealSaplingSpawnrate = 6
		#
		# How many times to attempt to spawn a sapling when grass is bonemealed. (also max # of saplings which can spawn per bonemeal)
		# Increasing this value too high may cause performance issues as it is not optimized for a large number of spawn attempts.
		# The probability of a sapling appearing is 1 - (((1 - ((plantableBlocksInRadius/147) * 1/bonemealSaplingSpawnRate))) ^ bonemealSaplingSpawnAttempts)
		# Default value is 2
		#Range: 1 ~ 1000
		bonemealSaplingSpawnAttempts = 2
		#
		# Whether or not saplings can convert to dead bushes in high light levels in the desert
		# Default value is true
		desertSaplingsCanBecomeDeadBush = true
		#
		# How many times out of 100 a sapling will become a dead bush instead of a tree at light level 15 in the desert
		# Default value is 75
		#Range: 1 ~ 100
		desertSaplingsMaxDeathrate = 75
		#
		# How many times out of 100 a sapling will become a dead bush instead of a tree at light level 10 in the desert
		# Default value is 25
		#Range: 1 ~ 100
		desertSaplingsMinDeathrate = 25
		#
		# Whether or not Endermen can place cocoa. This overrides any changes to enderman_holdable for cocoa and works with MobGreifing turned off if set to true
		# Default value is true
		endermenCanPickupAndPlaceCocoa = true
		#
		# Whether or not spiders (cave, regular, and most likely any moded spiders decended from the Minecraft spider) can spawn cobwebs under certain conditions
		# If enabled, they can spawn cobwebs next to leaves and logs, spawners, and other cobwebs (6 cardinal directions, not diagonals) provided
		# that the light level that they're in is between webSpinningMinLightLevel and webSpinningMaxLightLevel, inclusive
		# Default value is true
		spidersCanSpinWebs = true
		#
		# The maximum light level, inclusive, at which spiders can spawn cobwebs attached to logs, leaves, spawners, or other webs
		# For reference, spiders stop being aggressive somewhere between light levels 9 and 12. Every wiki has conflicting info, and it would take a lot of math
		# for me to figure out an approximation because it looks like they use the light level of the model which takes neighbor's light levels into account
		# Fun Fact: Spiders irl prefer to spin webs at dusk
		# Default value is 12
		#Range: 0 ~ 15
		webSpinningMaxLightLevel = 12
		#
		# The minimum light level, inclusive, at which spiders can spawn cobwebs attached to logs, leaves, spawners, or other webs
		# Consider setting this value to 0 if you want webs around spider spawners to expand organically
		# Default value is 8
		#Range: 0 ~ 15
		webSpinningMinLightLevel = 8
		#
		# Unfortunately, too many factors can go into the frequency of web spinning so this will have to remain a 'magic' number
		# When a spider is considering starting the task of spinning a web, it picks a random number between 0 and 100,000, and if it's under the
		# value determined by this config, it will start spinning the web.
		# This, however, is not the only factor as the spider may choose a different task instead, and other mods can add their own tasks with different weights
		# For reference I spawned ~6 spiders at noon in a roofed forest and came back to ~8 webs 20 minutes later with this set to 500, but when placed in
		# a room made of logs and leaves there were 10 webs within about a minute
		# Default value is 500
		#Range: 0 ~ 100000
		webSpinningFrequency = 500
		#
		# Allows spiders to create webs anywhere, removing the restriction on needing to be next to a log, leaves, or other cobwebs
		# Ironically, this will most likely improve performance since it will bypass the check, but I would suggest lowering the max light level if this is enabled
		# since you will probably get tired of removing webs from your base rather quickly.
		# Default value is false
		websEverywhere = false

