
["Dog Render"]
	#Enables the particle effect on Dire Level 30 dogs.
	enable_dire_particles = true
	#When enabled, dogs with points in pack puppy will have chests on their side.
	render_chest = true
	#If disabled will use the default minecraft wolf skin for all dog textures.
	enable_dt_textures = true
	#When enabled, dogs with points in guard dog will have armour.
	render_armour = false
	#When enabled, dogs with points in wolf mount will have a saddle on.
	render_saddle = true
	#When enabled, Dogs will have wings when at level 5 pillow paw.
	render_wings = false
	#When enabled, Dogs will show blood texture while incapacitated.
	render_incapacitated_overlay = true

