
["Configs for Dreadsteel"]
	#Dreadsteel helmet's armor value (Default = 10)
	"Helmet armor" = 10
	#Dreadsteel chestplate's armor value (Default = 15)
	"Chestplate armor" = 15
	#Dreadsteel leggings's armor value (Default = 12)
	"Leggings armor" = 12
	#Dreadsteel boots' armor value (Default = 9)
	"Boots armor" = 9
	#Dreadsteel armor piece toughness (Default = 8)
	"Armor toughness" = 8
	#Dreadsteel armor piece knockback resistance (Default = 0.25)
	"Armor knockback resistance" = 0.25
	#Dreadsteel Scythe's attack damage (also Projectile's damage) (Default = 50)
	"Scythe attack damage" = 50
	#Can the Dreadsteel Armor's stats be modified with this config? (Default = true)
	"Armor stats check" = true
	#Can the Dreadsteel Scythe's attack damage (and Projectile's damage) be modified with this config? (Default = true)
	"Scythe stats check" = true

