
["Miscellaneous Settings"]
	#----------------------------------------------------------------------------------------------------+
	# Enables the dungeon crawl developer tools. Do not use this for normal gameplay.
	#
	enable_tools = false
	#----------------------------------------------------------------------------------------------------+
	# Enables extended debug logging to help detecting errors. Enabled by default.
	#
	extended_debug = true

["World Generation"]
	#----------------------------------------------------------------------------------------------------+
	# Makes the entire dungeon solid, preventing caves, ravines, etc... from interfering with the dungeon.
	#
	solid = false
	#----------------------------------------------------------------------------------------------------+
	# Whether falling blocks like sand or gravel should drop down after being placed during dungeon generation.
	#
	tick_falling_blocks = true

["Dungeon Settings"]
	#----------------------------------------------------------------------------------------------------+
	# Whether the dungeons should have secret rooms or not.
	#
	secret_rooms = true
	#----------------------------------------------------------------------------------------------------+
	#
	#Whether the dungeons should generate at a fixed height or not. Enable this if the dungeons are generating too high.
	fixed_generation_height = false
	#----------------------------------------------------------------------------------------------------+
	# Whether loot tables of certain spawner entities should be overwritten.
	# For example, wither skeletons from dungeon spawners will never drop skulls if this is enabled.
	#
	overwrite_entity_loot_tables = true
	#----------------------------------------------------------------------------------------------------+
	# Whether the hell stage should be built with blocks from the overworld instead from the nether.
	#
	no_nether_blocks = false
	#----------------------------------------------------------------------------------------------------+
	# The activation range for the spawners in the dungeons.
	#
	#Range: 1 ~ 64
	spawner_activation_range = 12
	#----------------------------------------------------------------------------------------------------+
	# The number of different entities per spawner. Increasing the number increases the diversity of the monster equipment.
	#
	#Range: 1 ~ 128
	spawner_entities = 6
	#----------------------------------------------------------------------------------------------------+
	# Whether custom mob spawners with equipment, etc.. should be used.
	#
	custom_spawners = true
	#----------------------------------------------------------------------------------------------------+
	# Whether mobs from spawners should despawn naturally or not.
	#
	natural_despawn = true

