
#Item Configuration
[item_configuration]
	#Set the durability for melee weapons. [0-1024, default: 250
	#Range: 0 ~ 1024
	meleeWeaponDurability = 250
	#Set the durability for artifacts. [0-1024, default: 64
	#Range: 0 ~ 1024
	artifactDurability = 64

#General Mod Configuration
[general_mod_configuration]
	#Enable Weaponsmith, Fletcher, Armorer and Leatherworker Villagers trading Dungeons Gear items. 
	#If you have other mods messing with the trades of those professions or simply don't want it, disable this feature. [true / false]
	enableVillagerTrades = true
	#The emerald value for an artifact [0-64, default: 24]
	#Range: 0 ~ 64
	artifactValue = 32
	#Enable applying enchantments from this mod on non-Dungeons gear using the Enchanting Table. 
	#If you don't want your enchantments to become too cluttered for non-Dungeons gear, or simply don't like it, disable this feature. 
	#You can still use the anvil to put the enchantments onto them and have them work correctly. [true / false]
	enableEnchantsOnNonDungeonsGear = false
	#The emerald value for a common weapon or armor [0-64, default: 12]
	#Range: 0 ~ 64
	commonItemValue = 24
	#Enable applying enchantments together to create combinations would  be considered too overpowered. 
	#If you don't want overpowered enchantment combinations, like Sharpness and Committed on a sword, disable this feature. [true / false]
	enableOverpoweredEnchantmentCombos = false
	#Enable the mass addition of Dungeons Gear items to various vanilla loot tables by the mod itself. 
	#If you prefer to write your own loot pools via datapack or simply don't want it, disable this feature. [true / false]
	enableDungeonsGearLoot = false
	#The emerald value for a unique weapon or armor [0-64, default: 24]
	#Range: 0 ~ 64
	uniqueItemValue = 32
	#Enable the salvaging of Dungeons Gear items by shift-right clicking villagers with the item in your hand. 
	#If you have other mods messing with shift-right clicking villagers or simply don't want it, disable this feature. [true / false]
	enableSalvaging = true
	#Add enchantments that should be prevented from being applied to any gear. 
	#To do so, enter their registry names.
	enchantmentBlacklist = ["dungeons_gear:melee_aura", "dungeons_gear:gravity_pulse"]
	#Add enchantments that should be designated as treasure-only. 
	#To do so, enter their registry names.
	treasureOnlyEnchantments = []
	#Enable melee weapons appearing in chest loot and trades. 
	#If you Ewant to disable obtaining this mod's melee weapons, disable this feature. [true / false]
	enableMeleeWeaponLoot = true
	#Enable ranged weapons appearing in chest loot and trades. 
	#If you want to disable obtaining this mod's ranged weapons, disable this feature. [true / false]
	enableRangedWeaponLoot = true
	#Enable armors appearing in chest loot and trades. 
	#If you want to disable obtaining this mod's armors, disable this feature. [true / false]
	enableArmorLoot = true
	#Enable artifacts appearing in chest loot and trades. 
	#If you want to disable obtaining this mod's artifacts, disable this feature. [true / false]
	enableArtifactLoot = true
	#Enable melee weapons appearing in their own tab in the creative menu. 
	#Disabling this feature puts them in the COMBAT tab. [true / false]
	enableMeleeWeaponTab = true
	#Enable ranged weapons appearing in their own tab in the creative menu. 
	#Disabling this feature puts them in the COMBAT tab. [true / false]
	enableRangedWeaponTab = true
	#Enable armors appearing in their own tab in the creative menu. 
	#Disabling this feature puts them in the COMBAT tab. [true / false]
	enableArmorTab = true
	#Enable artifacts appearing in their own tab in the creative menu. 
	#Disabling this feature puts them in the COMBAT tab. [true / false]
	enableArtifactTab = true
	#Enable Librarian Villagers trading books enchanted with this mod's enchantments. 
	#Disable this feature if you want to prevent this. [true / false]
	enableEnchantmentTrades = true
	#Enable enchantments from this mod appearing in any type of generated loot. 
	#Disable this feature if you want to prevent this. [true / false]
	enableEnchantmentLoot = true
	#Enable Friendly Fire on Pets 
	#If you dislike (or outright hate) your pets and would like to kill them, enable this feature. [true / false]
	enableFriendlyPetFire = false
	#Enables the experimental features.
	#If you like living on the edge with broken items, enable this feature. [true / false]
	enableExperimental = false

#Compatibility Configuration
[compatibility_configuration]
	#Enable Elenai Dodge 2 compatibility. Effects that trigger on jump will now trigger on dodge. 
	#Does nothing if Elenai Dodge is not installed. [true / false]
	enableElenaiDodgeCompat = true
	#Enable Project: War Dance compatibility. 
	#Dual wield weapon offhand functions are suppressed in favor of using War Dance's offhand attacks. 
	#Block reach attributes are added to spears so they benefit from skills. 
	#Does nothing if Project: War Dance is not installed. [true / false]
	enableProjectWarDanceCompat = true

#Combat Configuration
[combat_configuration]
	#Enable area of effects also being applied to players. 
	#If you do not want area of effects being applied to other players, disable this feature. [true / false]
	enableAreaOfEffectOnPlayers = false
	#Add entities that will never be targeted by aggressive Dungeons Gear effects. 
	#To do so, enter their registry names.
	effectTargetBlacklist = ["minecraft:chicken", "minecraft:cow", "minecraft:pig", "minecraft:sheep", "minecraft:bee", "minecraft:wolf", "minecraft:fox", "minecraft:villager", "minecraft:horse", "minecraft:donkey", "minecraft:mooshroom", "minecraft:parrot", "minecraft:ocelot", "minecraft:rabbit", "minecraft:squid", "minecraft:strider", "minecraft:turtle", "minecraft:salmon", "minecraft:cod", "minecraft:pufferfish", "minecraft:tropical_fish", "minecraft:dolphin", "minecraft:panda", "minecraft:polar_bear", "minecraft:bat", "minecraft:trader_llama"]

#Common Loot Table Configuration
[common_loot_table_configuration]
	#Add gear from this mod to loot tables considered common. 
	#To do so, enter the full path of the specific loot table, or the path of the folder containing the loot tables.
	#You can also write an incomplete path, and the mod will add to loot tables containing that incomplete path.
	commonLootTables = ["minecraft:chests/abandoned_mineshaft", "minecraft:chests/shipwreck", "minecraft:chests/desert_pyramid"]
	#Use this list to prevent specific loot tables from getting common loot. 
	#To do so, enter the full path of the specific loot table.
	commonLootTablesBlacklist = []

#Enchantment Specific Configuration
[enchantment_specific_configuration]
	#The decimal base chance for a busy bee to spawn [0.0-1.0, default: 0.1]
	#Range: 0.0 ~ 1.0
	busyBeeBaseChance = 0.1
	#The decimal chance per level added for a busy bee to spawn [0.0-1.0, default: 0.1]
	#Range: 0.0 ~ 1.0
	busyBeeChancePerLevel = 0.1
	#The decimal chance per level added for a tumble bee to spawn [0.0-1.0, default: 0.1]
	#Range: 0.0 ~ 1.0
	tumbleBeeChancePerLevel = 0.1
	#The decimal chance for rampaging to trigger [0.0-1.0, default: 0.1]
	#Range: 0.0 ~ 1.0
	rampagingChance = 0.1
	#The duration in ticks (20ticks = 1 second) per level added for rampaging. [0-10000, default: 100]
	#Range: 0 ~ 10000
	rampagingDuration = 100
	#The duration in ticks (20ticks = 1 second) per level added for rushdown. [0-10000, default: 20]
	#Range: 0 ~ 10000
	rushdownDuration = 20
	#The duration in ticks (20ticks = 1 second) for weakening. [0-10000, default: 100]
	#Range: 0 ~ 10000
	weakeningDuration = 100
	#The application distance in blocks for weakening. [0-10000, default: 5]
	#Range: 0 ~ 10000
	weakeningDistance = 5
	#The decimal base multiplier on the victim's max health for leeching [0.0-5.0, default: 0.2]
	#Range: 0.0 ~ 5.0
	leechingBaseMultiplier = 0.2
	#The multiplier increase per level for leeching [0.0-5.0, default: 0.2]
	#Range: 0.0 ~ 5.0
	leechingMultiplierPerLevel = 0.2
	#The max stacks for dynamo. [0-10000, default: 20]
	#Range: 0 ~ 10000
	dynamoMaxStacks = 20
	#Multiplier per level applied to the damage. damage * (1 + (configValue*Stacks)) [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	dynamoDamageMultiplierPerStack = 0.1
	#The decimal base multiplier on the damage for max damage committed.  [0.0-5.0, default: 1.25]
	#Range: 0.0 ~ 5.0
	committedBaseMultiplier = 1.25
	#The multiplier increase per level for max damage committed [0.0-5.0, default: 0.25]
	#Range: 0.0 ~ 5.0
	committedMultiplierPerLevel = 0.25
	#The duration in ticks (20ticks = 1 second) for freezing. [0-10000, default: 60]
	#Range: 0 ~ 10000
	freezingDuration = 60
	#The decimal chance for Soul Siphon to trigger [0.0-1.0, default: 0.05]
	#Range: 0.0 ~ 1.0
	soulSiphonChance = 0.05
	#The amount of souls per trigger of Soul Siphon. Each souls will give a value based on Soul Gathering. [0-100, default: 2]
	#Range: 0 ~ 100
	soulSiphonSoulsPerLevel = 2
	#The decimal chance for Chains to trigger [0.0-1.0, default: 0.3]
	#Range: 0.0 ~ 1.0
	chainsChance = 0.3
	#The decimal chance for Radiance to trigger [0.0-1.0, default: 0.2]
	#Range: 0.0 ~ 1.0
	radianceChance = 0.0
	#The decimal chance for Thundering to trigger [0.0-1.0, default: 0.3]
	#Range: 0.0 ~ 1.0
	thunderingChance = 0.3
	#The base damage for Thundering [0-10000, default: 5]
	#Range: 0 ~ 10000
	thunderingBaseDamage = 5
	#Multiplier per level damage to healing conversion. [0.0-5.0, default: 0.25]
	#Range: 0.0 ~ 5.0
	altruisticDamageToHealingPerLevel = 0.25
	#The decimal base multiplier on the minions's damage for beast boss [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	beastBossBaseMultiplier = 0.1
	#The multiplier increase per level for beast boss [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	beastBossMultiplierPerLevel = 0.1
	#The amount of damage per trigger of Beast burst. Each trigger causes an explosion around each minion [0-100, default: 5]
	#Range: 0 ~ 100
	beastBurstDamagePerLevel = 5
	#The duration in ticks of the speed boost applied by Beast Surge. [0-10000, default: 200]
	#Range: 0 ~ 10000
	beastSurgeDuration = 200
	#The decimal base multiplier on the damage for cowardice [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	cowardiceBaseMultiplier = 0.1
	#The multiplier increase per level for cowardice [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	cowardiceMultiplierPerLevel = 0.1
	#The chance per level for deflect to trigger [0.0-5.0, default: 0.2]
	#Range: 0.0 ~ 5.0
	deflectChancePerLevel = 0.2
	#The multiplier increase per level for Focus Enchantments [0.0-5.0, default: 0.25]
	#Range: 0.0 ~ 5.0
	focusMultiplierPerLevel = 0.25
	#The multiplier increase per level for Frenzied [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	frenziedMultiplierPerLevel = 0.1
	#The decimal base pull strength for Gravity Pulse [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	gravityPulseBaseStrength = 0.1
	#The strength increase per level for Gravity Pulse [0.0-5.0, default: 0.1]
	#Range: 0.0 ~ 5.0
	gravityPulseStrengthPerLevel = 0.1
	#The decimal base duration for Potion Barrier [0-10000, default: 60]
	#Range: 0 ~ 10000
	potionBarrierBaseDuration = 60
	#The duration increase per level for Potion Barrier [0-10000, default: 20]
	#Range: 0 ~ 10000
	potionBarrierDurationPerLevel = 20
	#The multiplier to max health for reckless. Balanced as a negative number. [-5.0-5.0, default: -0.6]
	#Range: -5.0 ~ 5.0
	recklessMaxHealthMultiplier = -0.6
	#The decimal base multiplier on the damage for reckless [-5.0-5.0, default: 0.2]
	#Range: -5.0 ~ 5.0
	recklessAttackDamageBaseMultiplier = 0.2
	#The multiplier increase per level for reckless [-5.0-5.0, default: 0.2]
	#Range: -5.0 ~ 5.0
	recklessAttackDamageMultiplierPerLevel = 0.2
	#The multiplier increase per level for exploding [-5.0-5.0, default: 0.2]
	#Range: -5.0 ~ 5.0
	explodingMultiplierPerLevel = 0.2
	#The chance for Poison Cloud to trigger [-5.0-5.0, default: 0.3]
	#Range: -5.0 ~ 5.0
	prospectorChancePerLevel = 0.0

#Fancy Loot Table Configuration
[fancy_loot_table_configuration]
	#Add gear from this mod to loot tables considered uncommon. 
	#To do so, enter the full path of the specific loot table, or the path of the folder containing the loot tables.
	#You can also write an incomplete path, and the mod will add to loot tables containing that incomplete path.
	fancyLootTables = ["minecraft:chests/jungle_temple", "minecraft:chests/nether_bridge", "minecraft:chests/simple_dungeon"]
	#Use this list to prevent specific loot tables from getting uncommon loot. 
	#To do so, enter the full path of the specific loot table.
	fancyLootTablesBlacklist = ["minecraft:chests/jungle_temple_dispenser"]

#Obsidian Loot Table Configuration
[obsidian_loot_table_configuration]
	#Add gear from this mod to loot tables considered rare. 
	#To do so, enter the full path of the specific loot table, or the path of the folder containing the loot tables.
	#You can also write an incomplete path, and the mod will add to loot tables containing that incomplete path.
	obsidianLootTables = ["minecraft:chests/stronghold", "minecraft:chests/underwater_ruin", "minecraft:chests/pillager_outpost", "minecraft:chests/end_city_treasure", "minecraft:chests/igloo_chest", "minecraft:chests/woodland_mansion", "minecraft:chests/buried_treasure", "minecraft:chests/bastion"]
	#Use this list to prevent specific loot tables from getting rare loot. 
	#To do so, enter the full path of the specific loot table.
	obsidianLootTableBlacklist = []

#Loot Table Configuration
[loot_table_configuration]
	#Add gear from this mod to loot tables considered to belong to no actual environment. 
	#To do so, enter the full path of the specific loot table, or the path of the folder containing the loot tables.
	#You can also write an incomplete path, and the mod will add to loot tables containing that incomplete path.
	basicLootTables = ["minecraft:chests/abandoned_mineshaft", "minecraft:chests/stronghold", "minecraft:chests/simple_dungeon", "minecraft:chests/pillager_outpost", "minecraft:chests/woodland_mansion", "minecraft:village/village_armorer", "minecraft:village/village_tannery", "minecraft:village/village_temple", "minecraft:village/village_weaponsmith", "minecraft:village/village_plains_house", "minecraft:village/village_savanna_house"]
	#Use this list to prevent specific loot tables from getting loot. 
	#To do so, enter the full path of the specific loot table.
	basicLootTablesBlacklist = []
	#Add gear from this mod to loot tables considered to belong to the desert environment. 
	#To do so, enter the full path of the specific loot table, or the path of the folder containing the loot tables.
	#You can also write an incomplete path, and the mod will add to loot tables containing that incomplete path.
	desertLootTables = ["minecraft:chests/desert_pyramid", "minecraft:village/village_desert_house"]
	#Use this list to prevent specific loot tables from getting loot. 
	#To do so, enter the full path of the specific loot table.
	desertLootTablesBlacklist = []
	#Add gear from this mod to loot tables considered to belong to the ocean environment. 
	#To do so, enter the full path of the specific loot table, or the path of the folder containing the loot tables.
	#You can also write an incomplete path, and the mod will add to loot tables containing that incomplete path.
	oceanLootTables = ["minecraft:chests/shipwreck", "minecraft:chests/underwater_ruin"]
	#Use this list to prevent specific loot tables from getting loot. 
	#To do so, enter the full path of the specific loot table.
	oceanLootTablesBlacklist = ["minecraft:chests/buried_treasure"]
	#Add gear from this mod to loot tables considered to belong to cold environment chests. 
	#To do so, enter the full path of the specific loot table, or the path of the folder containing the loot tables.
	#You can also write an incomplete path, and the mod will add to loot tables containing that incomplete path.
	coldLootTables = ["minecraft:chests/igloo_chest", "minecraft:village/village_snowy_house", "minecraft:village/village_taiga_house"]
	#Use this list to prevent specific loot tables from getting loot. 
	#To do so, enter the full path of the specific loot table.
	coldLootTablesBlacklist = []
	#Add gear from this mod to loot tables considered to belong to the jungle environment. 
	#To do so, enter the full path of the specific loot table, or the path of the folder containing the loot tables.
	#You can also write an incomplete path, and the mod will add to loot tables containing that incomplete path.
	jungleLootTables = ["minecraft:chests/jungle_temple"]
	#Use this list to prevent specific loot tables from getting loot. 
	#To do so, enter the full path of the specific loot table.
	jungleLootTablesBlacklist = []
	#Add gear from this mod to loot tables considered to belong to the nether environment. 
	#To do so, enter the full path of the specific loot table, or the path of the folder containing the loot tables.
	#You can also write an incomplete path, and the mod will add to loot tables containing that incomplete path.
	netherLootTables = ["minecraft:chests/nether_bridge", "minecraft:chests/bastion", "minecraft:chests/ruined_portal"]
	#Use this list to prevent specific loot tables from getting loot. 
	#To do so, enter the full path of the specific loot table.
	netherLootTablesBlacklist = []
	#Add gear from this mod to loot tables considered to belong to the end environment. 
	#To do so, enter the full path of the specific loot table, or the path of the folder containing the loot tables.
	#You can also write an incomplete path, and the mod will add to loot tables containing that incomplete path.
	endLootTables = ["minecraft:chests/end_city_treasure"]
	#Use this list to prevent specific loot tables from getting loot. 
	#To do so, enter the full path of the specific loot table.
	endLootTablesBlacklist = []

#Effect Specific Configuration
[effect_specific_configuration]
	#The damage caused by Party Starter. [0-10000, default: 4]
	#Range: 0 ~ 10000
	partyStarterDamage = 4

#Artifact Specific Configuration
[artifact_specific_configuration]
	#Entities that can not be converted by Love Medallion.
	loveMedallionBlacklist = ["minecraft:ender_dragon", "minecraft:elder_guardian", "minecraft:wither"]

