
#Dynamic Lights Settings
[Settings]

	[Settings."Lighting Settings"]
		"Quality Mode (OFF, SLOW, FAST, REALTIME)" = "REALTIME"
		"Dynamic Entity Lighting" = true
		"Dynamic TileEntity Lighting" = true
		"Only Update On Position Change" = true

