
[controls]
	#Enable to make dodging left, right or backwards require a double tap, and forwards require a tap of the dodge button.
	double_tap = false
	#How many system ticks you have between double tapping (these are faster than Minecraft ticks).
	#Range: > 1
	double_tap_ticks = 200
	#Enable to make dodging forwards require a double tap (Must have double tap mode enabled)
	double_tap_forwards = false

[hud]
	#Whether to show the feathers in the UI.
	show_hud = true
	#Whether to enable compatibility hud. This will fix issues with the dodge bar disappearing in some instances, but is disabled as it may cause it to look out of place in others.
	compatibility_hud = false
	#Whether to show the tutorial on joining a new world.
	tutorial = false
	#Whether to show armor weight tooltips. If Quark is installed, please restart the game after disabling or enabling 'Quark Settings -> Client -> Visual Stat Display'.
	tooltips = true
	#Whether the Dodge Gui fades out when it's full.
	fadeout = false
	#Whether the Dodge Gui flashes when the player attempts to dodge when they haven't got enough feathers or too high a weight.
	flash = false
	#The X-Offset of the Feather Bar.
	#Range: > -2147483648
	x_offset = 0
	#The Y-Offset of the Feather Bar.
	#Range: > -2147483648
	y_offset = 0

