
[balance]
	#The force of the player's dodge before any multipliers have been applied. This value is very sensitive.
	#Range: 0.0 ~ 1.7976931348623157E308
	force = 0.6
	#How high the player is pushed from the ground when dodging. This value is proportional distance dodged due to friction.
	#Range: 0.0 ~ 1.7976931348623157E308
	verticality = 0.25
	#How much exhaustion is added when dodging. For reference, sprinting adds 0.01 exhaustion per meter, and the Hunger effect adds 0.1 per second.
	#Range: 0.0 ~ 40.0
	exhaustion = 0.4
	#How many half drumsticks the player needs to dodge. The default six is the same as sprinting.
	#Range: -1 ~ 20
	hunger = 6
	#Whether the player can dodge whilst sneaking.
	enable_whilst_sneaking = false
	#Whether the player can dodge whilst blocking.
	enable_whilst_blocking = false
	#Whether the player can dodge whilst airborne.
	enable_whilst_airborne = false
	#How many in-game ticks of invincibility the player has after dodging. 20 ticks is 1 second.
	#Range: 0 ~ 100
	invincibility_ticks = 10
	#Potions that prevent the player from dodging. Insert values in the format modid:potion,modid:potion. Idea Credit: SandwichHorror
	potion_blacklist = ""

[feathers]
	#How many half feathers dodging requires.
	#Range: 0 ~ 20
	cost = 2
	#The amount of ticks required to regenerate half a feather. Please only change this when you have full feathers.
	#Range: > 1
	regen_rate = 80
	#Whether to enable 'Half Feathers'. Instead of weight values rounding down, they will instead show as a half feather. These can be used if the 'Cost' value is set to an odd number.
	half_feathers = false
	#How many half feathers dodging in midair requires. [Enable Whilst Airborne must be Enabled]
	#Range: 0 ~ 20
	airborne_cost = 4

[weight]
	#The weight of each item of Armor. This Overrides the automatically generated values. Each 'Steel Feather' is equivalent to a weight of 2. Insert values as such: modid:itemname=value,modid:itemname=value. Any item with a weight over 24 will not show its weight as a tooltip. Idea Credit: SandwichHorror
	weights = "minecraft:leather_boots=1,minecraft:leather_leggings=2,minecraft:leather_chestplate=3,minecraft:leather_helmet=1,minecraft:iron_boots=2,minecraft:iron_leggings=3,minecraft:iron_chestplate=5,minecraft:iron_helmet=3,minecraft:diamond_boots=3,minecraft:diamond_leggings=4,minecraft:diamond_chestplate=6,minecraft:diamond_helmet=3,minecraft:golden_boots=2,minecraft:golden_leggings=2,minecraft:golden_chestplate=3,minecraft:golden_helmet=2,minecraft:chainmail_boots=2,minecraft:chainmail_leggings=2,minecraft:chainmail_chestplate=3,minecraft:chainmail_helmet=2,minecraft:elytra=2,minecraft:netherite_boots=4,minecraft:netherite_leggings=5,minecraft:netherite_chestplate=7,minecraft:netherite_helmet=4,minecraft:turtle_helmet=1"

[misc]
	#Whether the Player is notified when the Endurance Effect is overpowered by the Heavy Effect.
	message = true
	#Whether the Player dodges further in the Nether.
	nether = true
	#Whether the Player's dodge is weaker in the End.
	end = true
	#Whether the Player's dodge creates a puff of smoke.
	particles = true
	#Whether to use TAN integration.
	enable_tough_as_nails = true

[integration]
	#If Tough as Nails is installed: How much exhaustion (thirst) regenerating a feather costs. Idea Credit: ArtyArtyArtemis
	#Range: 0.0 ~ 40.0
	tough_as_nails_cost = 2.0

