#Range: > 1
DURABILITY_DOUBLE_UPGRADE = 400
#Range: > 1
DURABILITY_TRIPLE_UPGRADE = 400
#Range: > 1
DURABILITY_ARROW_COST_UPGRADE = 400
#Range: > 1
DURABILITY_HEAL_FROM_DAMAGE_UPGRADE = 400
#Range: > 1
DURABILITY_FIRE_UPGRADE = 400
#Range: > 1
DURABILITY_FREEZE_UPGRADE = 400
#Range: > 1
DURABILITY_WATER_UPGRADE = 400
#Range: > 1
DURABILITY_BRIDGE_UPGRADE = 400
#Range: > 1
DURABILITY_ENDER_UPGRADE = 400
#Range: > 1
DURABILITY_LIGHTNING_UPGRADE = 400
#Range: > 1
DURABILITY_EXPLOSIVE_UPGRADE = 400
#Range: > 1
DURABILITY_PUSH_UPGRADE = 400
#Range: > 1
DURABILITY_FLY_UPGRADE = 400
#Range: > 1
DURABILITY_METEOR_UPGRADE = 400
#Range: > 1
DURABILITY_ENERGY_UPGRADE = 400

[STONE_BOW]
	durability = 434
	#Range: 0.0 ~ 1.7976931348623157E308
	velocityMultiplier = 3.0
	#Range: 0.0 ~ 1.7976931348623157E308
	inaccuracy = 1.0
	#Range: 0.0 ~ 1.7976931348623157E308
	time = 18.0
	#Range: 0.0 ~ 1.7976931348623157E308
	damage = 1.0

[IRON_BOW]
	durability = 534
	#Range: 0.0 ~ 1.7976931348623157E308
	velocityMultiplier = 3.5
	#Range: 0.0 ~ 1.7976931348623157E308
	inaccuracy = 1.0
	#Range: 0.0 ~ 1.7976931348623157E308
	time = 16.0
	#Range: 0.0 ~ 1.7976931348623157E308
	damage = 2.0

[GOLD_BOW]
	durability = 300
	#Range: 0.0 ~ 1.7976931348623157E308
	velocityMultiplier = 4.25
	#Range: 0.0 ~ 1.7976931348623157E308
	inaccuracy = 0.5
	#Range: 0.0 ~ 1.7976931348623157E308
	time = 10.0
	#Range: 0.0 ~ 1.7976931348623157E308
	damage = 0.0

[DIAMOND_BOW]
	durability = 750
	#Range: 0.0 ~ 1.7976931348623157E308
	velocityMultiplier = 3.75
	#Range: 0.0 ~ 1.7976931348623157E308
	inaccuracy = 1.0
	#Range: 0.0 ~ 1.7976931348623157E308
	time = 15.0
	#Range: 0.0 ~ 1.7976931348623157E308
	damage = 5.0

[EMERALD_BOW]
	durability = 1500
	#Range: 0.0 ~ 1.7976931348623157E308
	velocityMultiplier = 4.0
	#Range: 0.0 ~ 1.7976931348623157E308
	inaccuracy = 1.0
	#Range: 0.0 ~ 1.7976931348623157E308
	time = 15.0
	#Range: 0.0 ~ 1.7976931348623157E308
	damage = 8.0

[ELECTRIC_BOW]
	durability = 534
	#Range: 0.0 ~ 1.7976931348623157E308
	velocityMultiplier = 3.5
	#Range: 0.0 ~ 1.7976931348623157E308
	inaccuracy = 1.0
	#Range: 0.0 ~ 1.7976931348623157E308
	time = 16.0
	#Range: 0.0 ~ 1.7976931348623157E308
	damage = 2.0

