
#Game settings
[settings]
	#Are tea bushes bonemealable?
	enableBoneMealTeaBush = false
	#Are coffee bushes bonemealable?
	enableBoneMealCoffeeBush = false
	#Chance of generating wild tea bushes. Smaller value = more frequent.
	#Range: > 0
	teaBushChance = 20
	#Chance of generating coffee bushes. Smaller value = more frequent.
	#Range: > 0
	coffeeBushChance = 2

