
["Jungle Creature Spawn Weight"]
	#Spawn weight of Pea Wees
	#Range: 1 ~ 1000
	pea_wee_spawn_weight = 5
	#Spawn weight of Vibra Wees
	#Range: 1 ~ 1000
	vibra_wee_spawn_weight = 3

["Swamp Creature Spawn Weight"]
	#Spawn weight of Flatback Suckers
	#Range: 1 ~ 1000
	flatback_sucker_spawn_weight = 1
	#Spawn weight of Swamp Muckers
	#Range: 1 ~ 1000
	swamp_mucker_spawn_weight = 1
	#Spawn weight of Mudhorses
	#Range: 1 ~ 1000
	mudhorse_spawn_weight = 3

["Mountain Creature Spawn Weight"]
	#Spawn weight of Siderol Whiskered Snails
	#Range: 1 ~ 1000
	siderol_whiskered_snail_spawn_weight = 1

["Beach Creature Spawn Weight"]
	#Spawn weight of Penglils
	#Range: 1 ~ 1000
	penglil_spawn_weight = 2

["Forest Creature Spawn Weight"]
	#Spawn weight of Flatback Leaf Snails
	#Range: 1 ~ 1000
	flatback_leaf_snail_spawn_weight = 2

["Cold Ocean Creature Spawn Weight"]
	#Spawn weight of Blu Wees
	#Range: 1 ~ 1000
	blu_wee_spawn_weight = 3
	#Spawn weight of Teal Arrowfish
	#Range: 1 ~ 1000
	teal_arrowfish_spawn_weight = 4
	#Spawn weight of Phantom Nudibranch
	#Range: 1 ~ 1000
	phantom_nudibranch_spawn_weight = 3

["Warm Ocean Creature Spawn Weight"]
	#Spawn weight of Banded Redback Shrimp
	#Range: 1 ~ 1000
	banded_redback_shrimp_spawn_weight = 3
	#Spawn weight of Ornate Bugfish
	#Range: 1 ~ 1000
	orante_bugfish_spawn_weight = 1
	#Spawn weight of Spindly Gem Crabs
	#Range: 1 ~ 1000
	spindly_gem_crab_spawn_weight = 7
	#Spawn weight of Rubber Belly Gliders
	#Range: 1 ~ 1000
	rubber_belly_glider_spawn_weight = 3

["Ocean Creature Spawn Weight"]
	#Spawn weight of High-finned Blue
	#Range: 1 ~ 1000
	high_finned_blue_spawn_weight = 2
	#Spawn weight of Gopjets
	#Range: 1 ~ 1000
	gopjet_spawn_weight = 1

["Lukewarm Ocean Creature Spawn Weight"]
	#Spawn weight of White Bull Crabs
	#Range: 1 ~ 1000
	white_bull_crabs_spawn_weight = 4
	#Spawn weight of Red Bull Crabs
	#Range: 1 ~ 1000
	red_bull_crabs_spawn_weight = 2

["Frozen Ocean Creature Spawn Weight"]
	#Spawn weight of Night Light Squid
	#Range: 1 ~ 1000
	night_light_squids_spawn_weight = 2

["River Creature Spawn Weight"]
	#Spawn weight of Wee Wees
	#Range: 1 ~ 1000
	wee_wee_spawn_weight = 2
	#Spawn weight of River Pebble Snails
	#Range: 1 ~ 1000
	river_pebble_snail_spawn_weight = 1
	#Spawn weight of Golden River Rays
	#Range: 1 ~ 1000
	golden_river_ray_spawn_weight = 2

[General]
	#Should Fins and Tails fish should appear in the fishing loot table?
	fins_fishing_loot = true

["Icy Spawn Weight"]
	#Spawn weight of Wherbles
	#Range: 1 ~ 1000
	wherble_spawn_weight = 3

