
["Exhaustion Control Values"]
	#Exhaustion Type: 0 = None-Speedonly, 1=Proportional, 2=Fixed
	#Range: 0 ~ 2
	exhaustionType = 1
	#Debug Level: 0 = Off, 1 = Log, 2 = Chat+Log
	#Range: 0 ~ 2
	debugLevel = 0
	#Normal Ore Behavior: true
	aNormalOre = true
	#Sideways and Upwards Digging Speed & Exhaustion Modifer: (none) 1.0 to (max) 32.0
	#Range: 1.0 ~ 32.0
	digModifier = 8.0
	#Downwards Speed & Exhaustion Modifer: (none) 1.0 to (max) 32.0
	#Range: 1.0 ~ 32.0
	downModifier = 1.03

["Tool Values 6464"]
	#Tool String 6464
	defaultToolsActual = "hbm:default,hbm:default_dimension,48,10.0;minecraft:torch,minecraft:overworld,48,0.2;minecraft:wooden_pickaxe,minecraft:overworld,48,8.0;minecraft:stone_pickaxe,minecraft:overworld,48,4.0;minecraft:iron_pickaxe,minecraft:overworld,48,2.0;minecraft:golden_pickaxe,minecraft:overworld,48,1.0;minecraft:diamond_pickaxe,minecraft:overworld,48,1.2;minecraft:netherite_pickaxe,minecraft:overworld,48,1.1;minecraft:wooden_shovel,minecraft:overworld,48,8.0;minecraft:stone_shovel,minecraft:overworld,48,4.0;minecraft:iron_shovel,minecraft:overworld,48,2.0;minecraft:golden_shovel,minecraft:overworld,48,1.0;minecraft:diamond_shovel,minecraft:overworld,48,1.2;minecraft:netherite_shovel,minecraft:overworld,48,1.1;minecraft:wooden_axe,minecraft:overworld,48,2.0;minecraft:stone_axe,minecraft:overworld,48,1.0;minecraft:iron_axe,minecraft:overworld,48,2.0;minecraft:golden_axe,minecraft:overworld,48,1.0;minecraft:diamond_axe,minecraft:overworld,48,1.2;minecraft:netherite_axe,minecraft:overworld,48,1.1;minecraft:iron_pickaxe,minecraft:the_nether,124,2.2;minecraft:netherite_pickaxe,minecraft:the_nether,124,1.0;"

["Blocks White List Values 6464"]
	#Blocks Whitelist String 6464
	defaultBlocksWhiteListActual = "ore_stone_variants:coal_ore;ore_stone_variants:iron_ore;ore_stone_variants:gold_ore;ore_stone_variants:diamond_ore;ore_stone_variants:lapis_ore;ore_stone_variants:redstone_ore;rockcandy:candy_ore;minecraft:oak_planks;minecraft:oak_fence;"

