
[health]
	#Show vanilla hearts
	healthVanilla = true
	#Colors for every 10 hearts (not counting the default red)
	#All values are written as hexadecimal RGB color in '#RRGGBB' format
	healthColors = ["#F06E14", "#F5DC23", "#2DB928", "#1EAFBE", "#7346E1", "#FA7DEB", "#EB375A", "#FF8278", "#AAFFFA", "#EBEBFF"]
	#Two alternating colors when poisoned
	#There can be one color in case vanilla poisoned heart is wanted
	healthPoisonColors = ["#739B00"]
	#Two alternating colors when withered
	#There can be one color in case vanilla withered heart is wanted
	healthWitherColors = ["#0F0F0F"]
	#Two alternating colors when frozen
	#There can be one color in case vanilla frozen heart is wanted
	healthFrozenColors = ["#3E70E6"]

[absorption]
	#Show vanilla hearts
	absorptionVanilla = true
	#Colors for every 10 hearts (not counting the default yellow)
	#All values are written as hexadecimal RGB color in '#RRGGBB' format
	absorptionColors = ["#E1FA9B", "#A0FFAF", "#AAFFFA", "#AACDFF", "#D7B4FF", "#FAA5FF", "#FFB4B4", "#FFAA7D", "#D7F0FF", "#EBFFFA"]
	#Two alternating colors when poisoned
	absorptionPoisonColors = ["#BFF230", "#7AA15A"]
	#Two alternating colors when withered
	absorptionWitherColors = ["#787061", "#73625C"]
	#Two alternating colors when freezing
	absorptionFrozenColors = ["#90D136", "#36D183"]

[qol]
	#Display absorption in the same row as health
	#Absorption hearts start directly after the last health heart.
	absorptionOverHealth = false

	[qol.counter]
		#Visualizes health/absorption to left of the hearts.
		#Allowed Values: OFF, ALWAYS, ON_CHANGE
		displayMode = "OFF"
		#Text displayed next to health. Minecraft chat color codes are allowed.
		#Available variables:
		#    "[HEALTH]": Current health.
		#    "[MAX]": Max health.
		#    "[HEARTS]": Current health in hearts.
		#    "[MAX_HEARTS]": Max health in hearts.
		#    "[ROW]": Current health row.
		#    "[MAX_ROW]": Max health row.
		textHealth = "ยง4[HEALTH]ยง7/ยง2[MAX]"
		#Text displayed next to absorption. Minecraft chat color codes are allowed.
		#In case 'absorptionOverHealth' is true, this text is displayed at the same position as or left of 'textHealth'.
		#Available variables:
		#    "[ABSORPTION]": Current absorption.
		#    "[HEARTS]": Current absorption in hearts.
		#    "[ROW]": Current absorption row.
		textAbsorption = "ยง6[ABSORPTION]"

