
#Settings for world gen
["World Gen"]
	#Average chunk separation between companion houses
	#Range: > 11
	averageHouseSeparation = 20

["Companion config"]
	#Toggle friendly fire
	friendlyFire = false
	#Toggle fall damage for companions
	fallDamage = true

