
#Settings for world gen
["World Gen"]
	#Average chunk separation between companion houses
	#Range: > 11
	averageHouseSeparation = 20

["Companion config"]
	#Toggles fall damage for companions
	fallDamage = true
	#Toggles friendly fire between companions
	friendlyFireCompanions = false
	#Toggles friendly fire between player and companion
	friendlyFirePlayer = true
	#Toggles whether companions spawn with armor
	spawnArmor = true
	#Toggles whether companions spawn with a weapon
	spawnWeapon = true
	#Sets the base health of each companion. Companions spawn with up to +-4 from the base health
	#Range: > 5
	baseHealth = 50
	#Toggles whether companions ask for food if their health goes below half.
	lowHealthFood = true
	#Toggles whether companions alert you if a creeper is nearby.
	creeperWarning = true

