
[Base]
	#No more boring 2D Area of Effect Clouds
	"Enable Area Effect Cloud 3D" = true
	#A few fixes
	"Enable Fixes" = true

	#No more boring 2D Area of Effect Clouds
	[Base."Area Effect Cloud 3D"]
		#If true, vanilla Area of Effect Clouds will be replaced with 3D versions of them
		"Replace Vanilla Area of Effect Clouds" = true

	#A few fixes
	[Base.Fixes]
		#If true, mobs will have their follow range fixed. https://bugs.mojang.com/browse/MC-145656
		"Fix Follow Range" = true
		#Removes the random bonus health given to Leader Zombies. In vanilla it's useless since doesn't work. https://minecraft.fandom.com/wiki/Attribute#Vanilla_modifiers
		"Remove Zombies Bonus Health" = true
		#When affected by slowness the player can still jump really far away. When true, jumps length will be calculated based off player's movement speed.
		"Fix Jump Movement Factor" = true
		#The fix for Jump Movement Factor is applied only when the player is slowed down. If false, the player will jump really farther when going faster.
		"Fix Jump Movement Factor Slowdown Only" = true

