
#Ore Generation
[oregen]

	#Tin ore generation.
	[oregen.Tin_oregen]
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		oreChances = 7
		#Max size of the vein.
		#Range: 1 ~ 256
		veinSize = 8
		#Minimum Y spawn
		#Range: -64 ~ 256
		minY = 40
		#Maximum Y spawn
		#Range: -64 ~ 256
		maxY = 180
		#The dimensions that this ore should spawn in as a list (default ["minecraft:overworld"])
		dimensions = ["minecraft:overworld"]

	#Silver ore generation.
	[oregen.Silver_oregen]
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		oreChances = 4
		#Max size of the vein.
		#Range: 1 ~ 256
		veinSize = 8
		#Minimum Y spawn
		#Range: -64 ~ 256
		minY = -64
		#Maximum Y spawn
		#Range: -64 ~ 256
		maxY = 64
		#The dimensions that this ore should spawn in as a list (default ["minecraft:overworld"])
		dimensions = ["minecraft:overworld"]

	#Lead ore generation.
	[oregen.Lead_oregen]
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		oreChances = 4
		#Max size of the vein.
		#Range: 1 ~ 256
		veinSize = 8
		#Minimum Y spawn
		#Range: -64 ~ 256
		minY = -32
		#Maximum Y spawn
		#Range: -64 ~ 256
		maxY = 50
		#The dimensions that this ore should spawn in as a list (default ["minecraft:overworld"])
		dimensions = ["minecraft:overworld"]

	#Sapphire ore generation.
	[oregen.Sapphire_oregen]
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		oreChances = 4
		#Max size of the vein.
		#Range: 1 ~ 256
		veinSize = 3
		#Minimum Y spawn
		#Range: -64 ~ 256
		minY = -64
		#Maximum Y spawn
		#Range: -64 ~ 256
		maxY = 50
		#The dimensions that this ore should spawn in as a list (default ["minecraft:overworld"])
		dimensions = ["minecraft:overworld"]

	#Quartz ore generation.
	[oregen.Quartz_oregen]
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		oreChances = 90
		#Max size of the vein.
		#Range: 1 ~ 256
		veinSize = 5
		#Minimum Y spawn
		#Range: -64 ~ 256
		minY = -64
		#Maximum Y spawn
		#Range: -64 ~ 256
		maxY = 256
		#The dimensions that this ore should spawn in as a list (default ["minecraft:overworld"])
		dimensions = ["minecraft:overworld"]

#Mob Spawn Configuration
[mob_spawns]

	#Deer spawn config.
	[mob_spawns.Deer_spawn]
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 6
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 2
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 4
		#List of biome types to spawn.
		biomes = "forest,icy,taiga,plains,"

	#Green Sprout spawn config.
	[mob_spawns."Green Sprout_spawn"]
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 2
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 1
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 2
		#List of biome types to spawn.
		biomes = "jungle,river,forest,beach,"

	#Tan Sprout spawn config.
	[mob_spawns."Tan Sprout_spawn"]
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 2
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 1
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 2
		#List of biome types to spawn.
		biomes = "jungle,river,forest,beach,"

	#Purple Sprout spawn config.
	[mob_spawns."Purple Sprout_spawn"]
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 2
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 1
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 2
		#List of biome types to spawn.
		biomes = "jungle,river,forest,beach,"

	#Red Sprout spawn config.
	[mob_spawns."Red Sprout_spawn"]
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 2
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 1
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 2
		#List of biome types to spawn.
		biomes = "jungle,river,forest,beach,"

	#Hell Sprout spawn config.
	[mob_spawns."Hell Sprout_spawn"]
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 2
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 1
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 2
		#List of biome types to spawn.
		biomes = "nether,"
		#how often a hell sprout should attempt to plant nether wart (1 in X, 0 for never)
		#Range: > 0
		chance = 100

	#Fennec spawn config.
	[mob_spawns.Fennec_spawn]
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 4
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 1
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 3
		#List of biome types to spawn.
		biomes = "sandy,hot,mesa,savanna,"

	#Beetle spawn config.
	[mob_spawns.Beetle_spawn]
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 5
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 2
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 4
		#List of biome types to spawn.
		biomes = "swamp,jungle,forest,plains,"

	#Frog spawn config.
	[mob_spawns.Frog_spawn]
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 6
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 2
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 4
		#List of biome types to spawn.
		biomes = "swamp,jungle,beach,river,"

	#Endermini spawn config.
	[mob_spawns.Endermini_spawn]
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 2
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 1
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 2
		#List of biome types to spawn.
		biomes = "end,"

	#Owl spawn config.
	[mob_spawns.Owl_spawn]
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 9
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 1
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 3
		#List of biome types to spawn.
		biomes = "taiga,extreme_hills,forest,icy,"

	#Lava Cat spawn config.
	[mob_spawns."Lava Cat_spawn"]
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 2
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 1
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 1
		#List of biome types to spawn.
		biomes = "nether,"

	#Silkworm spawn config.
	[mob_spawns.silkworm_spawn]
		#Whether or not silkworm eggs drop from leaves
		leafDrops = true
		#Chance to spawn whenever a leaf is broken (1 in X)
		leafDropChance = 65
		#Chance for silkworm eggs to spawn a silkworm (1 in X, 1 is guaranteed)
		successChance = 1
		#Chance per tick for silkworms to grown (1 in X)
		growthChance = 68

	#Duck spawn config.
	[mob_spawns.Duck_spawn]
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 5
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 1
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 4
		#List of biome types to spawn.
		biomes = "wet,swamp,river,beach,"

	#Clam spawn config.
	[mob_spawns.Clam_spawn]
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 2
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 1
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 1
		#List of biome types to spawn.
		biomes = "ocean,river,beach,swamp,wet,"
		#the chance of a clam spawning as an ender clam [0 to disable ender clams]
		#Range: > 0
		enderChance = 31
		#the upper value of initial age for a clam
		#Range: > 0
		initialAge = 2300
		#the max age for a clam
		#Range: > 0
		maxAge = 5100

#Hat Configuration
[hat_config]
	#Spawn frequency (1 in X chances per tick while spawn conditions are met, -1 for not at all)
	#Range: > 0
	antler_frequency = 50
	#How many hearts under maximum health the player needs to be for a deer to spawn (-1 for any value under maximum health
	#Range: > -1
	antler_threshold = -1
	#How much a Spirit Deer should heal for
	#Range: 0.5 ~ 1.7976931348623157E308
	antler_healing = 2.0
	#How long a duration Regeneration should be applied for
	#Range: > 1
	antler_regen_duration = 130
	#What amplifier should be applied to the Regeneration effect (0 = I, 1 = II, etc)
	#Range: > 0
	antler_regen_amplifier = 1
	#How much of a health bonus wearing the hat should give (-1 for no bonus, 2 for a single heart, 4 for two hearts, etc
	#Range: 0.5 ~ 1.7976931348623157E308
	antler_health_bonus = 4.0
	#How much damage to the antler hat spawning a spirit deer causes (-1 for no damage)
	#Range: > -1
	antler_damage = 1
	#How much of a damage to bonus should be provided by the mask (-1 for none)
	#Range: -1.0 ~ 1.7976931348623157E308
	mask_bonus_damage = 0.3

#Armor Configuration
[armor_config]

	#Configuration for orichalcum armor
	[armor_config.orichalcum_armor]
		#Armor value for chest piece
		#Range: > 0
		chest_armor = 5
		#Armor value for feet piece
		#Range: > 0
		feet_armor = 1
		#Armor value for head piece
		#Range: > 0
		head_armor = 2
		#Armor value for legs piece
		#Range: > 0
		legs_armor = 3
		#Toughness for armor made of this material
		#Range: 0.0 ~ 1.7976931348623157E308
		toughness = 0.0

	#Configuration for carapace armor
	[armor_config.carapace_armor]
		#Armor value for chest piece
		#Range: > 0
		chest_armor = 6
		#Armor value for feet piece
		#Range: > 0
		feet_armor = 2
		#Armor value for head piece
		#Range: > 0
		head_armor = 2
		#Armor value for legs piece
		#Range: > 0
		legs_armor = 5
		#Toughness for armor made of this material
		#Range: 0.0 ~ 1.7976931348623157E308
		toughness = 0.0

	#Configuration for tin armor
	[armor_config.tin_armor]
		#Armor value for chest piece
		#Range: > 0
		chest_armor = 5
		#Armor value for feet piece
		#Range: > 0
		feet_armor = 1
		#Armor value for head piece
		#Range: > 0
		head_armor = 2
		#Armor value for legs piece
		#Range: > 0
		legs_armor = 4
		#Toughness for armor made of this material
		#Range: 0.0 ~ 1.7976931348623157E308
		toughness = 0.0

	#Configuration for antler armor
	[armor_config.antler_armor]
		#Armor value for chest piece
		#Range: > 0
		chest_armor = 0
		#Armor value for feet piece
		#Range: > 0
		feet_armor = 3
		#Armor value for head piece
		#Range: > 0
		head_armor = 0
		#Armor value for legs piece
		#Range: > 0
		legs_armor = 0
		#Toughness for armor made of this material
		#Range: 0.0 ~ 1.7976931348623157E308
		toughness = 1.0

	#Configuration for copper armor
	[armor_config.copper_armor]
		#Armor value for chest piece
		#Range: > 0
		chest_armor = 6
		#Armor value for feet piece
		#Range: > 0
		feet_armor = 2
		#Armor value for head piece
		#Range: > 0
		head_armor = 2
		#Armor value for legs piece
		#Range: > 0
		legs_armor = 5
		#Toughness for armor made of this material
		#Range: 0.0 ~ 1.7976931348623157E308
		toughness = 0.0

	#Configuration for silver armor
	[armor_config.silver_armor]
		#Armor value for chest piece
		#Range: > 0
		chest_armor = 5
		#Armor value for feet piece
		#Range: > 0
		feet_armor = 1
		#Armor value for head piece
		#Range: > 0
		head_armor = 2
		#Armor value for legs piece
		#Range: > 0
		legs_armor = 3
		#Toughness for armor made of this material
		#Range: 0.0 ~ 1.7976931348623157E308
		toughness = 0.0

	#Configuration for lead armor
	[armor_config.lead_armor]
		#Armor value for chest piece
		#Range: > 0
		chest_armor = 6
		#Armor value for feet piece
		#Range: > 0
		feet_armor = 2
		#Armor value for head piece
		#Range: > 0
		head_armor = 2
		#Armor value for legs piece
		#Range: > 0
		legs_armor = 5
		#Toughness for armor made of this material
		#Range: 0.0 ~ 1.7976931348623157E308
		toughness = 1.0

	#Configuration for sapphire armor
	[armor_config.sapphire_armor]
		#Armor value for chest piece
		#Range: > 0
		chest_armor = 8
		#Armor value for feet piece
		#Range: > 0
		feet_armor = 3
		#Armor value for head piece
		#Range: > 0
		head_armor = 3
		#Armor value for legs piece
		#Range: > 0
		legs_armor = 6
		#Toughness for armor made of this material
		#Range: 0.0 ~ 1.7976931348623157E308
		toughness = 2.0

#Feature Spawn Configuration
[feature_spawns]
	#Whether or not the aubergine loot table is injected into the grass seed table (default: false in favor of wild aubergine)
	seed_injection = false
	#Whether or not loot should be injected to Vanilla tables
	loot_injection = true

	#Charred Tree Generation
	[feature_spawns.charred_tree]
		#Number of charred trees per chunk (set to 0 to disable).
		#Range: 0.0 ~ 256.0
		chance = 0.02
		#List of biome types to spawn (default [SAVANNA,DEAD,FOREST,SANDY,WASTELAND], pass empty list for every biome
		biomes = "SAVANNA,DEAD,FOREST,SANDY,WASTELAND"
		#Which biome types this tree shouldn't spawn in (default END, NETHER)
		biomeRestrictions = "NETHER,END"
		#The dimensions that this feature should spawn in as a list (default ["minecraft:overworld"])
		dimensions = ["minecraft:overworld"]

	#Stonepetal Patch Generation
	[feature_spawns.stone_petal]
		#Number of tries per chunk to try placing stonepetals on stone (set to 0 to disable).
		#Range: 0 ~ 256
		tries = 7
		#Number of times per chunk to repeat trying to place stonepetals on stone
		#Range: 1 ~ 256
		repeats = 1
		#List of biome types to spawn (default [MOUNTAIN], pass empty list for every biome
		biomes = "MOUNTAIN"
		#Which biome types this tree shouldn't spawn in (default END, NETHER)
		biomeRestrictions = "NETHER,END"
		#The dimensions that this feature should spawn in as a list (default ["minecraft:overworld"])
		dimensions = ["minecraft:overworld"]

	#Wild Aubergine Generation
	[feature_spawns.wild_aubergine]
		#Number of tries per chunk to try placing wild aubergine (set to 0 to disable).
		#Range: 0 ~ 256
		tries = 20
		#Number of times per chunk to repeat trying to placing wild aubergine
		#Range: 1 ~ 256
		repeats = 1
		#List of biome types to spawn (default [PLAINS,FOREST,LUSH,HILLS,JUNGLE], pass empty list for every biome
		biomes = "PLAINS,FOREST,LUSH,HILLS,JUNGLE"
		#Which biome types this feature shouldn't spawn in (default END, NETHER)
		biomeRestrictions = "NETHER,END"
		#The dimensions that this feature should spawn in as a list (default ["minecraft:overworld"])
		dimensions = ["minecraft:overworld"]

