
#Disable features.
[Features]
	#Tool Information Tooltips enabled?
	toolInfoTooltip = true
	#Waila harvest level tooltip enabled?
	wailaHarvestLevel = true

#General configuration options
[General]
	#The harvest level names used by the Tool Info Tweak tooltips.
	harvestLevelNames = ["Stone", "Iron", "Diamond", "Obsidian", "Netherite", "Max"]

