
[general]
	#Determines which starting item a player gets on first world join. Valid values for this option are: "Starting House", "Moderate House", "Nothing". Server configuration overrides client.
	"Starting Item" = "Starting House"
	#Determines if the loft starter house is enabled. This house contains Nether materials in it's construction. Server configuration overrides client.
	"Enable Loft House" = false
	#Determines if the spawners for the Monster Masher building are included. Server configuration overrides client.
	"Include Spawners in Monster Masher" = false
	#Determines if the Preview buttons in structure GUIs and other structure previews functions are enabled. Client side only.
	"Include Structure Previews" = true
	#Determines if the mineshaft chest is included when building mineshafts for various structures.
	"Include Mineshaft Chest" = true
	#Determines if the bulldozer item can create drops when it clears an area.
	"Bulldozer Creates Drops" = false
	#Determines if water can be generated in structures when the current dimension is not the oveworld. Does not affect Nether
	"Include Water In Non-Overworld Dimesions" = false
	#Enable Automation Options For Moderate Farm
	"Enable Automation Options For Moderate Farm" = true
	#Play Sound When Generating Blueprint
	"Play Building Sound" = true

	[general."chest contents"]
		#Determines if a Stone Sword is added the the chest when the house is created.
		"Add Sword" = false
		#Determines if a Stone Axe is added the the chest when the house is created.
		"Add Axe" = false
		#Determines if a Stone Shovel is added the the chest when the house is created.
		"Add Shovel" = false
		#Determines if a Stone Hoe is added the the chest when the house is created.
		"Add Hoe" = false
		#Determines if a Stone Pickaxe is added the the chest when the house is created.
		"Add Pickaxe" = false
		#Determines if Leather Armor is added the the chest when the house is created.
		"Add Armor" = false
		#Determines if Bread is added the the chest when the house is created.
		"Add Food" = true
		#Determines if seeds, potatoes and carrots are added the the chest when the house is created.
		"Add Crops" = true
		#Determines if a stack of dirt is added the the chest when the house is created.
		"Add Dirt" = true
		#Determines if a stack of cobble is added the the chest when the house is created.
		"Add Cobblestone" = true
		#Determines if a set of oak saplings are added the the chest when the house is created.
		"Add Saplings" = true
		#Determines if a set of torches are added the the chest when the house is created.
		"Add Torches" = true

	[general."starter house"]
		#Determines if the bed is included in the starter house. When playing on a server, the server configuration is used
		"Add Bed" = true
		#Determines if the crafting table is included in the starter house. When playing on a server, the server configuration is used
		"Add Crafting Table" = false
		#Determines if the furnace is included in the starter house. When playing on a server, the server configuration is used
		"Add Furnace" = false
		#Determines if chests are included in the starter house. When playing on a server, the server configuration is used
		"Add Chests" = true
		#Determines if the chest contents is included in the starter house. When playing on a server, the server configuration is used
		"Add Chest Contents" = true
		#Determines if the mineshaft is included in the starter house. When playing on a server, the server configuration is used
		"Add Mineshaft" = true

	[general.recipes]
		#Determines if the recipe(s) associated with the Compressed Stone are enabled.
		"Compressed Stone" = true
		#Determines if the recipe(s) associated with the Compressed Glowstone are enabled.
		"Compressed Glowstone" = true
		#Determines if the recipe(s) associated with the Compressed Dirt are enabled.
		"Compressed Dirt" = true
		#Determines if the recipe(s) associated with the Compressed Chest are enabled.
		"Compressed Chest" = true
		#Determines if the recipe(s) associated with the Pile of Bricks are enabled.
		"Pile of Bricks" = true
		#Determines if the recipe(s) associated with the Warehouse are enabled.
		Warehouse = true
		#Determines if the recipe(s) associated with the Warehouse Upgrade are enabled.
		"Warehouse Upgrade" = true
		#Determines if the recipe(s) associated with the Advanced Warehouse are enabled.
		"Advanced Warehouse" = true
		#Determines if the recipe(s) associated with the Bundle of Timber are enabled.
		"Bundle of Timber" = true
		#Determines if the recipe(s) associated with the Nether Gate are enabled.
		"Nether Gate" = false
		#Determines if the recipe(s) associated with the Machinery Tower are enabled.
		"Machinery Tower" = true
		#Determines if the recipe(s) associated with the Defense Bunker are enabled.
		"Defense Bunker" = true
		#Determines if the recipe(s) associated with the Mineshaft Entrance are enabled.
		"Mineshaft Entrance" = true
		#Determines if the recipe(s) associated with the Ender Gateway are enabled.
		"Ender Gateway" = true
		#Determines if the recipe(s) associated with the Magic Temple are enabled.
		"Magic Temple" = false
		#Determines if the recipe(s) associated with the Instant Bridge are enabled.
		"Instant Bridge" = true
		#Determines if the recipe(s) associated with the Paper Lantern are enabled.
		"Paper Lantern" = true
		#Determines if the recipe(s) associated with the Compressed Obsidian are enabled.
		"Compressed Obsidian" = true
		#Determines if the recipe(s) associated with the Villager Houses are enabled.
		"Villager Houses" = true
		#Determines if the recipe(s) associated with the Phasic Block are enabled.
		"Phasic Block" = true
		#Determines if the recipe(s) associated with the Smart Glass are enabled.
		"Smart Glass" = true
		#Determines if the recipe(s) associated with the Green House are enabled.
		"Green House" = true
		#Determines if the recipe(s) associated with the Starting House are enabled.
		"Starting House" = true
		#Determines if the recipe(s) associated with the Glass Stairs are enabled.
		"Glass Stairs" = true
		#Determines if the recipe(s) associated with the Glass Slabs are enabled.
		"Glass Slabs" = true
		#Determines if the recipe(s) associated with the Moderate House are enabled.
		"Moderate House" = true
		#Determines if the recipe(s) associated with the Grassy Plains are enabled.
		"Grassy Plains" = true
		#Determines if the recipe(s) associated with the Aqua Base are enabled.
		"Aqua Base" = true
		#Determines if the recipe(s) associated with the Watch Tower are enabled.
		"Watch Tower" = true
		#Determines if the recipe(s) associated with the Bulldozer are enabled.
		Bulldozer = true
		#Determines if the recipe(s) associated with the Jail are enabled.
		Jail = true
		#Determines if the recipe(s) associated with the Saloon are enabled.
		Saloon = true
		#Determines if the recipe(s) associated with the Ski Lodge are enabled.
		"Ski Lodge" = true
		#Determines if the recipe(s) associated with the Windmill are enabled.
		Windmill = true
		#Determines if the recipe(s) associated with the Town Hall are enabled.
		"Town Hall" = true
		#Determines if the recipe(s) associated with the Heap of Timber are enabled.
		"Heap of Timber" = true
		#Determines if the recipe(s) associated with the Ton of Timber are enabled.
		"Ton of Timber" = true
		#Determines if the recipe(s) associated with the Workshop are enabled.
		Workshop = true
		#Determines if the recipe(s) associated with the Modern Buildings are enabled.
		"Modern Buildings" = false
		#Determines if the recipe(s) associated with the Swift Blade are enabled.
		"Swift Blade" = false
		#Determines if the recipe(s) associated with the Sickle are enabled.
		Sickle = false
		#Determines if the recipe(s) associated with the Dirt Recipes are enabled.
		"Dirt Recipes" = true
		#Determines if the recipe(s) associated with the Bunch Of Beets are enabled.
		"Bunch Of Beets" = true
		#Determines if the recipe(s) associated with the Bunch Of Carrots are enabled.
		"Bunch Of Carrots" = true
		#Determines if the recipe(s) associated with the Bunch Of Potatoes are enabled.
		"Bunch Of Potatoes" = true
		#Determines if the recipe(s) associated with the WoodenCrate are enabled.
		WoodenCrate = true
		#Determines if the recipe(s) associated with the Starter Farm are enabled.
		"Starter Farm" = true
		#Determines if the recipe(s) associated with the Moderate Farm are enabled.
		"Moderate Farm" = true
		#Determines if the recipe(s) associated with the Advanced Farm are enabled.
		"Advanced Farm" = false

