
#General settings
[general]
	#Weight of a basic case dropping
	#Range: 0 ~ 100
	basic_chance = 10
	#Weight of a golden case dropping
	#Range: 0 ~ 100
	gold_chance = 0
	#Weight of a titan case dropping
	#Range: 0 ~ 100
	titan_chance = 0
	#Chance of a case dropping #DEPRECATED
	#Range: 0 ~ 100
	total_chance = 0
	#Weight for a sword to drop from case
	#Range: 0 ~ 100
	sword_weight = 20
	#Weight for a pick to drop from case
	#Range: 0 ~ 100
	pick_weight = 5
	#Weight for a shovel to drop from case
	#Range: 0 ~ 100
	spade_weight = 5
	#Weight for and axe to drop from case
	#Range: 0 ~ 100
	axe_weight = 5
	#Weight for a bow to drop from case
	#Range: 0 ~ 100
	bow_weight = 8
	#Weight for any given piece of armor to drop from case
	#Range: 0 ~ 100
	armor_weight = 1
	#Monsters drop chance
	#Range: 0 ~ 1000
	monster_drops = 50
	#Animals drop chance
	#Range: 0 ~ 1000
	animal_drops = 0
	#Bosses drop chance
	#Range: 0 ~ 1000
	boss_drops = 1000
	#Allow anonymous data collection?
	data = false
	#Enable certain traits to be craftable.
	crafting_traits = true

#Textures
[textures]
	#Sword Textures
	#Range: 1 ~ 1000
	sword_textures = 47
	#Pickaxe Textures
	#Range: 1 ~ 1000
	pickaxe_textures = 17
	#Axe Textures
	#Range: 1 ~ 1000
	axe_textures = 11
	#Shovel Textures
	#Range: 1 ~ 1000
	shovel_textures = 8
	#Bow Textures
	#Range: 1 ~ 1000
	bow_textures = 6

#Case Distribution
[cases]
	#Basic Case common drop weight
	#Range: 0 ~ 100
	bsc_weight = 90
	#Basic Case rare drop weight
	#Range: 0 ~ 100
	bsr_weight = 10
	#Basic Case legendary drop weight
	#Range: 0 ~ 100
	bsl_weight = 0
	#Gold Case common drop weight
	#Range: 0 ~ 100
	brc_weight = 50
	#Gold Case rare drop weight
	#Range: 0 ~ 100
	brr_weight = 45
	#Gold Case legendary drop weight
	#Range: 0 ~ 100
	brl_weight = 5
	#Titan Case common drop weight
	#Range: 0 ~ 100
	btc_weight = 20
	#Titan Case rare drop weight
	#Range: 0 ~ 100
	btr_weight = 60
	#Titan Case legendary drop weight
	#Range: 0 ~ 100
	btl_weight = 20

#Tool Settings
[tools]
	#Minimum damage a sword can do.
	#Range: 0 ~ 100
	sword_damage = 5
	#Minimum speed a sword can have.
	#Range: -4.0 ~ 4.0
	sword_speed = -2.9
	#Minimum damage a throwable can do.
	#Range: 0 ~ 100
	throw_damage = 5
	#Minimum damage a pickaxe can do.
	#Range: 0 ~ 100
	pick_damage = 3
	#Minimum attack speed a pickaxe can have.
	#Range: -4.0 ~ 4.0
	pick_a_speed = -2.8
	#Minimum damage an axe can do.
	#Range: 0 ~ 100
	axe_damage = 7
	#Minimum attack speed an axe can have.
	#Range: -4.0 ~ 4.0
	axe_a_speed = -3.5
	#Minimum armor points armor can have.
	#Range: 0 ~ 100
	armor = 4
	#Minimum armor points armor can have.
	#Range: 0.0 ~ 100.0
	toughness = 0.1
	#Minimum damage a shovel can do.
	#Range: 0 ~ 100
	spade_damage = 3
	#Minimum attack speed a shovel can have.
	#Range: -4.0 ~ 4.0
	spade_a_speed = -2.8
	#Initital Rolls for traits/stats
	#Range: 0 ~ 100
	basic_rolls = 2
	#Range: 0 ~ 100
	gold_rolls = 4
	#Range: 0 ~ 100
	titan_rolls = 10
	#Initital Max XP for tools.
	#Range: 0 ~ 10000
	init_xp = 256
	#Odds of an item getting a buff rather than a trait on a stats roll (editor upgrade, tool init, etc.)
	#Range: 0 ~ 100
	trait_ratio = 5
	#Weight for a throwable weapon to drop from case
	#Range: 0 ~ 100
	throwing_weight = 6

#Traits Enabled
[traits]
	# Enabled?
	_enabled = true
	#Speedy Enabled?
	speedy_enabled = true
	#Bouncy Enabled?
	bouncy_enabled = false
	#Resistant Enabled?
	resistant_enabled = true
	#Fire Resistant Enabled?
	fire_resistant_enabled = true
	#Hastey Enabled?
	hastey_enabled = true
	#Lucky Enabled?
	lucky_enabled = true
	#Strong Enabled?
	strong_enabled = true
	#Insightful Enabled?
	insightful_enabled = true
	#Deep Breathing Enabled?
	deep_breathing_enabled = true
	#Regenerating Enabled?
	regenerating_enabled = true
	#Poisonous Enabled?
	poisonous_enabled = true
	#Withering Enabled?
	withering_enabled = true
	#Webbed Enabled?
	webbed_enabled = true
	#Blinding Enabled?
	blinding_enabled = true
	#Glittering Enabled?
	glittering_enabled = true
	#Blood Thirst Enabled?
	blood_thirst_enabled = true
	#Weakening Enabled?
	weakening_enabled = true
	#Floating Enabled?
	floating_enabled = true
	#Explosive Enabled?
	explosive_enabled = true
	#Filling Enabled?
	filling_enabled = false
	#Phasing Enabled?
	phasing_enabled = false
	#Soul Searching Enabled?
	soul_searching_enabled = true
	#Cloud Walker Enabled?
	cloud_walker_enabled = true
	#Giant Slayer Enabled?
	giant_slayer_enabled = false
	#Sharper Edge Enabled?
	sharper_edge_enabled = true
	#Enraged Enabled?
	enraged_enabled = true
	#Taming Enabled?
	taming_enabled = true
	#Fortified Enabled?
	fortified_enabled = false
	#Auto Smelt Enabled?
	auto_smelt_enabled = false
	#Excavating Enabled?
	excavating_enabled = false
	#Sun Bathing Enabled?
	sun_bathing_enabled = true
	#Rained Out Enabled?
	rained_out_enabled = true
	#Crowd Pleaser Enabled?
	crowd_pleaser_enabled = true
	#Sturdy Enabled?
	sturdy_enabled = true
	#Fierce Enabled?
	fierce_enabled = true
	#Stalky Enabled?
	stalky_enabled = true
	#Hailey's Wrath Enabled?
	"hailey's_wrath_enabled" = true
	#Ore Sight Enabled?
	ore_sight_enabled = false
	#Charged Enabled?
	charged_enabled = true
	#Long Legged Enabled?
	long_legged_enabled = true
	#Fire Storm Enabled?
	fire_storm_enabled = true
	#Twin Shooter Enabled?
	twin_shooter_enabled = false
	#End Arrows Enabled?
	end_arrows_enabled = true
	#Illuminated Enabled?
	illuminated_enabled = false
	#Locked Enabled?
	locked_enabled = true
	#Egg Hunt Enabled?
	egg_hunt_enabled = true
	#Glowing Enabled?
	glowing_enabled = false

