
#Here you can tweak some additional stuff this mod does
[General]
	#Chance 1 in X that a hostile entity drops either salve, a plaster or a bandage\nSet this to 0 if you want to disable entity drops
	#Range: 0 ~ 32767
	dropChance = 0
	#Amount of half hearts sleeping heals. Set to 0 to disable this feature
	#Range: 0.0 ~ 32767.0
	sleepHealAmount = 2.0
	#Set to true if you want to regenerate health without the use of healing items
	healthRegen = true

#Defines how often you're able to rightclick the item to heal yourself. Set the use count to 0 to disable the item.
[HealCount]
	#Use count for the salve item
	#Range: > 0
	salveHealCount = 4
	#Use count for the plaster item
	#Range: > 0
	plasterHealCount = 4
	#Use count for the bandage item
	#Range: > 0
	bandageHealCount = 6
	#Use count for the medkit item
	#Range: > 0
	medkitHealCount = 16
	#Use count for the enchanted medkit item
	#Range: > 0
	medkitEnchantedHealCount = 16

#Defines how much health the item restores on rightclick.
[HealAmount]
	#Salve heal amount
	#Range: 1.0 ~ 1.7976931348623157E308
	salveHealAmount = 1.0
	#Salve heal amount
	#Range: 1.0 ~ 1.7976931348623157E308
	plasterHealAmount = 1.0
	#Salve heal amount
	#Range: 1.0 ~ 1.7976931348623157E308
	bandageHealAmount = 1.0
	#Salve heal amount
	#Range: 1.0 ~ 1.7976931348623157E308
	medkitHealAmount = 2.0
	#Salve heal amount
	#Range: 1.0 ~ 1.7976931348623157E308
	medkitEnchantedHealAmount = 3.0

#Defines how long it takes for a healing item to get used.
[HealTime]
	#Use time for the salve item
	#Range: 0 ~ 72000
	salveUseTime = 5
	#Use count for the plaster item
	#Range: 0 ~ 72000
	plasterUseTime = 10
	#Use count for the bandage item
	#Range: 0 ~ 72000
	bandageUseTime = 20
	#Use count for the medkit item
	#Range: 0 ~ 72000
	medkitUseTime = 40
	#Use count for the enchanted medkit item
	#Range: 0 ~ 72000
	medkitEnchantedUseTime = 40

