#Determines if the 'Coyote Time' feature is enabled.
#'Coyote Time' allows the player to jump for a second or two after falling off of a block in order to stop themselves from falling into a pit.
#This will not allow the player to double jump, only jump when walking off of a block.
coyoteTimeEnabled = true
#Determines how long (in ticks) the player has to jump with 'Coyote Time' after falling off a block.
#Range: > 1
coyoteTimeTicks = 10
#Determines if the 'Second Chance' feature is enabled.
#'Second Chance' leaves the player at half a heart after taking fatal damage from a mob or explosion while at or above 7 hearts.
secondChanceEnabled = true
#Determines if the 'Second Chance' sound will play when the effect is activated.
secondChanceSound = true
#Determines if the 'Second Chance' feature will be activated by explosions.
secondChanceExplosions = true
#Determines if the 'Second Chance' feature will be activated by mobs.
secondChanceMobs = true
#Determines how much health the player must start with for 'Second Chance' to activate.
#Range: 0.5 ~ 1.7976931348623157E308
secondChanceActivationHealth = 13.5
#Determines how much health the player should be left with after 'Second Chance' activates.
#Range: 0.5 ~ 1.7976931348623157E308
secondChanceHealthRemainder = 1.0
#Determines if the 'Second Chance' feature will be activated by fall damage.
secondChanceFalls = false
#Determines if the 'Second Chance' feature will be activated by falling anvils.
secondChanceAnvils = false
#Determines if the 'Second Chance' feature will be activated by lightning.
secondChanceLightning = false
#Determines if the 'Second Chance' feature will be activated by crashing into a wall.
secondChanceElytraCrash = false
#Determines if the 'Second Chance' feature will be activated by falling blocks.
secondChanceFallingBlocks = false
#Determines if the 'Second Chance' feature will be activated by magic, such as potions.
secondChanceMagic = false
#Determines if the 'Second Chance' feature will be activated by players.
secondChancePlayers = false
#Determines if the 'Second Chance' feature will be activated by thrown tridents.
secondChanceTridents = false
#Determines if the 'Second Chance' feature will be activated by arrows.
secondChanceArrows = false
#Determines if the 'Second Chance' feature will be activated by fireworks.
secondChanceFireworks = false
#Determines if the 'Second Chance' feature will be activated by wither skulls.
secondChanceWitherSkulls = false
#Determines if the 'percentage of health' config values will be used instead of exact values.
usePercentConfig = false
#Determines what percent of health the player must start with for 'Second Chance' to activate.
#Range: 0.01 ~ 1.7976931348623157E308
secondChanceActivationPercent = 65.0
#Determines what percent health the player should be left with after 'Second Chance' activates.
#Range: 0.01 ~ 1.7976931348623157E308
secondChanceHealthPercent = 5.0

