
[dagger]
	#Disables all recipes for all Daggers.
	disable = false
	#Damage Multiplier for Daggers.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.0
	#Attack speed of Daggers.
	#Range: 0.0 ~ 4.0
	speed = 2.5
	#Base Damage of Daggers.
	#Range: 0.1 ~ 100.0
	base_damage = 2.5

[longsword]
	#Disables all recipes for all Longswords.
	disable = false
	#Damage Multiplier for Longswords.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.5
	#Attack speed of Longswords.
	#Range: 0.0 ~ 4.0
	speed = 1.399999976158142
	#Base Damage of Longswords.
	#Range: 0.1 ~ 100.0
	base_damage = 4.5

[katana]
	#Disables all recipes for all Katanas.
	disable = false
	#Damage Multiplier for Katanas.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 0.5
	#Attack speed of Katanas.
	#Range: 0.0 ~ 4.0
	speed = 2.0
	#Base Damage of Katanas.
	#Range: 0.1 ~ 100.0
	base_damage = 3.5

[saber]
	#Disables all recipes for all Sabers.
	disable = false
	#Damage Multiplier for Sabers.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 0.5
	#Attack speed of Sabers.
	#Range: 0.0 ~ 4.0
	speed = 1.600000023841858
	#Base Damage of Sabers.
	#Range: 0.1 ~ 100.0
	base_damage = 3.5

[rapier]
	#Disables all recipes for all Rapiers.
	disable = false
	#Damage Multiplier for Rapiers.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 0.5
	#Attack speed of Rapiers.
	#Range: 0.0 ~ 4.0
	speed = 2.4000000953674316
	#Base Damage of Rapiers.
	#Range: 0.1 ~ 100.0
	base_damage = 2.0

[greatsword]
	#Disables all recipes for all Greatswords.
	disable = false
	#Damage Multiplier for Greatswords.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.5
	#Attack speed of Greatswords.
	#Range: 0.0 ~ 4.0
	speed = 1.399999976158142
	#Base Damage of Greatswords.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0

[club]
	#Disables all recipes for all Clubs.
	disable = false
	#Damage Multiplier for Clubs.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.0
	#Attack speed of Clubs.
	#Range: 0.0 ~ 4.0
	speed = 1.2999999523162842
	#Base Damage of Clubs.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0

[cestus]
	#Disables all recipes for all Cestusae.
	disable = false
	#Damage Multiplier for Cestusae.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 0.5
	#Attack speed of Cestusae.
	#Range: 0.0 ~ 4.0
	speed = 3.5
	#Base Damage of Cestusae.
	#Range: 0.1 ~ 100.0
	base_damage = 2.0

[battle_hammer]
	#Disables all recipes for all Battle Hammers.
	disable = false
	#Damage Multiplier for Battle Hammers.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 2.0
	#Attack speed of Battle Hammers.
	#Range: 0.0 ~ 4.0
	speed = 0.800000011920929
	#Base Damage of Battle Hammers.
	#Range: 0.1 ~ 100.0
	base_damage = 5.0

[warhammer]
	#Disables all recipes for all Warhammers.
	disable = false
	#Damage Multiplier for Warhammers.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.5
	#Attack speed of Warhammers.
	#Range: 0.0 ~ 4.0
	speed = 1.100000023841858
	#Base Damage of Warhammers.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0

[spear]
	#Disables all recipes for all Spears.
	disable = false
	#Damage Multiplier for Spears.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 0.5
	#Attack speed of Spears.
	#Range: 0.0 ~ 4.0
	speed = 1.399999976158142
	#Base Damage of Spears.
	#Range: 0.1 ~ 100.0
	base_damage = 5.5

[halberd]
	#Disables all recipes for all Halberds.
	disable = false
	#Damage Multiplier for Halberds.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.5
	#Attack speed of Halberds.
	#Range: 0.0 ~ 4.0
	speed = 1.2000000476837158
	#Base Damage of Halberds.
	#Range: 0.1 ~ 100.0
	base_damage = 5.0

[pike]
	#Disables all recipes for all Pikes.
	disable = false
	#Damage Multiplier for Pikes.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.0
	#Attack speed of Pikes.
	#Range: 0.0 ~ 4.0
	speed = 1.399999976158142
	#Base Damage of Pikes.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0

[lance]
	#Disables all recipes for all Lances.
	disable = false
	#Damage Multiplier for Lances.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.0
	#Attack speed of Lances.
	#Range: 0.0 ~ 4.0
	speed = 1.0
	#Base Damage of Lances.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0

[throwing_knife]
	#Disables all recipes for all Throwing Knives.
	disable = false
	#Damage Multiplier for Throwing Knives.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.0
	#Attack speed of Throwing Knives.
	#Range: 0.0 ~ 4.0
	speed = 2.5
	#Base Damage of Throwing Knives.
	#Range: 0.1 ~ 100.0
	base_damage = 1.5
	#Charge time in ticks for Throwing Knives.
	#Range: 1 ~ 1000
	charge_ticks = 5

[tomahawk]
	#Disables all recipes for all Tomahawks.
	disable = false
	#Damage Multiplier for Tomahawks.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.5
	#Attack speed of Tomahawks.
	#Range: 0.0 ~ 4.0
	speed = 0.8999999761581421
	#Base Damage of Tomahawks.
	#Range: 0.1 ~ 100.0
	base_damage = 2.0
	#Charge time in ticks for Tomahawks.
	#Range: 1 ~ 1000
	charge_ticks = 8

[javelin]
	#Disables all recipes for all Javelins.
	disable = false
	#Damage Multiplier for Javelins.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.0
	#Attack speed of Javelins.
	#Range: 0.0 ~ 4.0
	speed = 1.2000000476837158
	#Base Damage of Javelins.
	#Range: 0.1 ~ 100.0
	base_damage = 1.5
	#Charge time in ticks for Javelins.
	#Range: 1 ~ 1000
	charge_ticks = 10

[boomerang]
	#Disables all recipes for all Boomerangs.
	disable = false
	#Damage Multiplier for Boomerangs.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.0
	#Attack speed of Boomerangs.
	#Range: 0.0 ~ 4.0
	speed = 2.0
	#Base Damage of Boomerangs.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0
	#Charge time in ticks for Boomerangs.
	#Range: 1 ~ 1000
	charge_ticks = 5

[battleaxe]
	#Disables all recipes for all Battleaxes.
	disable = false
	#Damage Multiplier for Battleaxes.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 2.0
	#Attack speed of Battleaxes.
	#Range: 0.0 ~ 4.0
	speed = 1.0
	#Base Damage of Battleaxes.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0

[flanged_mace]
	#Disables all recipes for all Flanged Maces.
	disable = false
	#Damage Multiplier for Flanged Maces.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.5
	#Attack speed of Flanged Maces.
	#Range: 0.0 ~ 4.0
	speed = 1.2000000476837158
	#Base Damage of Flanged Maces.
	#Range: 0.1 ~ 100.0
	base_damage = 3.0

[glaive]
	#Disables all recipes for all Glaives.
	disable = false
	#Damage Multiplier for Glaives.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.5
	#Attack speed of Glaives.
	#Range: 0.0 ~ 4.0
	speed = 1.0
	#Base Damage of Glaives.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0

[quarterstaff]
	#Disables all recipes for all Quarterstaves.
	disable = false
	#Damage Multiplier for Quarterstaves.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.5
	#Attack speed of Quarterstaves.
	#Range: 0.0 ~ 4.0
	speed = 1.399999976158142
	#Base Damage of Quarterstaves.
	#Range: 0.1 ~ 100.0
	base_damage = 3.0

[copper]
	#Set to true to disable copper weapons
	disable = false
	#Durability for copper weapons
	#Range: 1 ~ 100000
	durability = 200
	#Base Damage for copper weapons
	#Range: 0.1 ~ 100.0
	base_damage = 1.5

[tin]
	#Set to true to disable tin weapons
	disable = false
	#Durability for tin weapons
	#Range: 1 ~ 100000
	durability = 180
	#Base Damage for tin weapons
	#Range: 0.1 ~ 100.0
	base_damage = 1.75

[bronze]
	#Set to true to disable bronze weapons
	disable = true
	#Durability for bronze weapons
	#Range: 1 ~ 100000
	durability = 320
	#Base Damage for bronze weapons
	#Range: 0.1 ~ 100.0
	base_damage = 2.0

[steel]
	#Set to true to disable steel weapons
	disable = true
	#Durability for steel weapons
	#Range: 1 ~ 100000
	durability = 480
	#Base Damage for steel weapons
	#Range: 0.1 ~ 100.0
	base_damage = 2.5

[silver]
	#Set to true to disable silver weapons
	disable = false
	#Durability for silver weapons
	#Range: 1 ~ 100000
	durability = 480
	#Base Damage for silver weapons
	#Range: 0.1 ~ 100.0
	base_damage = 1.5

[invar]
	#Set to true to disable invar weapons
	disable = true
	#Durability for invar weapons
	#Range: 1 ~ 100000
	durability = 440
	#Base Damage for invar weapons
	#Range: 0.1 ~ 100.0
	base_damage = 2.200000047683716

[platinum]
	#Set to true to disable platinum weapons
	disable = true
	#Durability for platinum weapons
	#Range: 1 ~ 100000
	durability = 1024
	#Base Damage for platinum weapons
	#Range: 0.1 ~ 100.0
	base_damage = 3.5

[electrum]
	#Set to true to disable electrum weapons
	disable = true
	#Durability for electrum weapons
	#Range: 1 ~ 100000
	durability = 180
	#Base Damage for electrum weapons
	#Range: 0.1 ~ 100.0
	base_damage = 2.0

[nickel]
	#Set to true to disable nickel weapons
	disable = true
	#Durability for nickel weapons
	#Range: 1 ~ 100000
	durability = 200
	#Base Damage for nickel weapons
	#Range: 0.1 ~ 100.0
	base_damage = 2.0

[lead]
	#Set to true to disable lead weapons
	disable = false
	#Durability for lead weapons
	#Range: 1 ~ 100000
	durability = 240
	#Base Damage for lead weapons
	#Range: 0.1 ~ 100.0
	base_damage = 2.0

[explosives]
	#Disables terrain damage for explosives in this mod such as Dynamite and Explosive Arrows. Is overridden by the 'mobGriefing' gamerule.
	disable_terrain_damage = false
	#Disables all recipes for explosive related items
	disable_recipe = false
	#Time (in ticks) it takes for Dynamite to explode
	#Range: 20 ~ 600
	fuse_ticks_dynamite = 60
	#Explosion strength for Dynamite
	#Range: 0.10000000149011612 ~ 10.0
	explosion_strength_dynamite = 2.0

[projectiles]
	#Bows in this blacklist will not get Arrows pulled out of the Arrow Quiver. Use the registry ID of the bow to add to this. e.g. "minecraft:bow"
	quiver_bow_blacklist = ["botania:crystal_bow"]
	#Disables Recipes for all new Arrows.
	disable_new_arrow_recipes = false
	#Disables all variants of the Arrow Quiver and the Bolt Quiver in this mod
	disable_quiver_recipes = false
	#Disables Recipes for both Diamond Arrows and Diamond Bolts.
	disable_diamond_ammo_recipes = false

	[projectiles.wood_arrow]
		#Base damage for wood arrows
		#Range: 0.1 ~ 100.0
		base_damage = 0.20000000298023224
		#Range muliplier for wood arrows
		#Range: 0.1 ~ 100.0
		range_multiplier = 1.5

	[projectiles.iron_arrow]
		#Base damage for iron arrows
		#Range: 0.1 ~ 100.0
		base_damage = 3.0
		#Range muliplier for iron arrows
		#Range: 0.1 ~ 100.0
		range_multiplier = 0.75

	[projectiles.diamond_arrow]
		#Base damage for diamond arrows
		#Range: 0.1 ~ 100.0
		base_damage = 3.5
		#Range muliplier for diamond arrows
		#Range: 0.1 ~ 100.0
		range_multiplier = 1.25

	[projectiles.bolt]
		#Base damage for bolts
		#Range: 0.1 ~ 100.0
		base_damage = 4.0
		#Range muliplier for bolts
		#Range: 0.1 ~ 100.0
		range_multiplier = 1.0
		#Armor Piercing factor for bolts
		#Range: 0.0 ~ 1.0
		armor_piercing_factor = 0.25

	[projectiles.diamond_bolt]
		#Base damage for diamond bolts
		#Range: 0.1 ~ 100.0
		base_damage = 5.0
		#Range muliplier for diamond bolts
		#Range: 0.1 ~ 100.0
		range_multiplier = 1.0
		#Armor Piercing factor for diamond bolts
		#Range: 0.0 ~ 1.0
		armor_piercing_factor = 0.5

	[projectiles.explosive]
		#Base damage for explosive arrows
		#Range: 0.1 ~ 10.0
		base_damage = 2.0
		#Range muliplier for explosive arrows
		#Range: 0.1 ~ 100.0
		range_multiplier = 1.0

[loot]
	#Set to false to disable spawning Diamond Weapons in End City chests via loot table injection
	add_diamond_weapons_to_end_city = true
	#Chance for Zombies to spawn with Iron Melee Weapons on all difficulties apart from Hard and Hardcore
	#Range: 0.0 ~ 1.0
	zombie_with_melee_spawn_chance_normal = 0.05000000074505806
	#Chance for Zombies to spawn with Iron Melee Weapons on Hard or Hardcore difficulty
	#Range: 0.0 ~ 1.0
	zombie_with_melee_spawn_chance_hard = 0.25
	#Set to false to disable spawning Iron Weapons in Village Weaponsmith chests via loot table injection
	add_iron_weapons_to_village_blacksmith = true
	#Set to true to disable spawning a Zombie with any weapons from this mod
	disable_spawning_zombie_with_weapon = false
	#Set to false to disable spawning Longbow and Heavy Crossbow-related loot in Village Fletcher chests via loot table injection
	add_bow_and_crossbow_loot_to_village_fletcher = true
	#Set to true to disable the new mob heads from being dropped from mobs using the Decapitate Weapon Trait from this mod.
	disable_new_head_drops = false

[trading]
	#Set to true to disable Villagers (Weaponsmiths and Fletchers) from trading weapons from this mod
	disable = false

[traits]

	[traits.damage_bonus]
		#Changes the "Chest Damage Bonus" Weapon Trait multiplier value
		#Range: 1.0 ~ 50.0
		chest_multiplier = 2.0
		#Changes the "Riding Damage Bonus" Weapon Trait multiplier value
		#Range: 1.0 ~ 50.0
		riding_multiplier = 2.25
		#Changes the "Throwing Damage Bonus" Weapon Trait multiplier value
		#Range: 1.0 ~ 50.0
		throw_multiplier = 2.0
		#Changes the "Chest Damage Bonus" Weapon Trait multiplier value
		#Range: 1.0 ~ 50.0
		throw_javelin_multiplier = 3.0
		#Changes the "Unarmored Damage Bonus" Weapon Trait multiplier value
		#Range: 1.0 ~ 50.0
		unarmored_multiplier = 3.0
		#If set to true, any damage bonus that checks for armor will only apply if the hit mob has less than the total armor value threshold, while still checking for armor
		check_armor_value = false
		#Max armor value allowed for any damage bonus that checks for armor to apply, without any armor equipped
		#Range: 1.0 ~ 50.0
		max_armor_value = 1.0
		#Changes the "Undead Damage Bonus" Weapon Trait multiplier value
		#Range: 1.0 ~ 50.0
		undead_multiplier = 1.5
		#Changes the "Backstab Damage Bonus" Weapon Trait multiplier value
		#Range: 1.0 ~ 50.0
		backstab_multiplier = 4.0

	[traits.damage_absorption]
		#Changes the percentage of damage absorbed by the "Damage Absorption" Weapon Trait
		#Range: 0.0 ~ 1.0
		damage_absorption_factor = 0.25

	[traits.reach]
		#Changes the reach of any weapons with the "Reach I" Weapon Trait
		#Range: 5.0 ~ 15.0
		reach1_value = 5.0
		#Changes the reach of any weapons with the "Reach II" Weapon Trait
		#Range: 5.0 ~ 15.0
		reach2_value = 5.0

	[traits.sweep]
		#Changes the percentage of damage inflicted to enemies when sweep attacked on weapons with the "Sweep II" Weapon Trait
		#Range: 0.0 ~ 100.0
		sweep2_percentage = 50.0
		#Changes the percentage of damage inflicted to enemies when sweep attacked on weapons with the "Sweep III" Weapon Trait
		#Range: 0.0 ~ 100.0
		sweep3_percentage = 100.0

	[traits.armor_pierce]
		#Changes the percentage of damage that ignores armor on weapons with the "Armor Piercing" Weapon Trait
		#Range: 0.0 ~ 100.0
		percentage = 50.0

	[traits.quick_strike]
		#Tweaks the hurt resistance ticks for weapons that use the "Quick Strike" Weapon Trait
		#Range: 10 ~ 20
		hurt_resistance_ticks = 14

	[traits.decapitate]
		#Tweaks the percentage of Skull drops from weapons with the "Decapitate" Weapon Trait
		#Range: 0.0 ~ 100.0
		skull_drop_percentage = 25.0

[longbow]
	#Disables all recipes for all Longbows.
	disable = false

[heavy_crossbow]
	#Disables all recipes for all Heavy Crossbows.
	disable = false

[parrying_dagger]
	#Disables all recipes for all Parrying Daggers.
	disable = false
	#Attack speed of Parrying Daggers.
	#Range: 0.0 ~ 4.0
	speed = 2.5
	#Base Damage of Parrying Daggers.
	#Range: 0.1 ~ 100.0
	base_damage = 2.5
	#Damage Multiplier for Parrying Daggers.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.0

[scythes]
	#Disables all recipes for all Scythes.
	disable = false
	#Attack speed of Scythes.
	#Range: 0.0 ~ 4.0
	speed = 1.0
	#Base Damage of Scythes.
	#Range: 0.1 ~ 100.0
	base_damage = 5.0
	#Damage Multiplier for Scythes.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.0

[jei]
	#Set to true to forcibly show disabled items in JEI, even if they cannot be crafted. Should be useful for modpack makers defining their own recipes.
	force_show_disabled_items = false

