
["It Takes A Pillage - Config"]
	#Replace naturally spawning Iron Golems with Clay Golems?
	"Replace Iron Golems" = false
	#Remove Bad Omen effect after drinking milk?
	"Milk Removes Bad Omen" = false
	#Pillage Sieges occur at night?
	"Enable Pillage Sieges" = true
	#Clay Golem replacement rate (Peaceful difficulty)
	"Peaceful Replacement Rate" = 0.0
	#Clay Golem replacement rate (Easy difficulty)
	"Easy Replacement Rate" = 0.1
	#Clay Golem replacement rate (Normal difficulty)
	"Normal Replacement Rate" = 0.1
	#Clay Golem replacement rate (Hard difficulty)
	"Hard Replacement Rate" = 0.1

