
["Traveler's Titles"]

	###########################################################################################################
	## General settings.
	###########################################################################################################
	["Traveler's Titles".General]
		# If enabled, dimensions without ceilings (like the Overworld) will only display titles when the player is exposed to the skylight.
		# This prevents dimension & biome titles from showing while the user is underground.
		# Default: true
		"Only Show Titles When Exposed To Skylight" = true

	###########################################################################################################
	## Biome Title settings.
	###########################################################################################################
	["Traveler's Titles"."Biome Titles"]
		"Enable Biome Titles" = true
		# How long the fade-in text effect lasts, in ticks.
		# 20 ticks = 1 second.
		# Default: 10
		"Text Fade-In Time" = 10
		# How long the text displays, in ticks.
		# 20 ticks = 1 second.
		# Default: 50
		"Text Display Time" = 50
		# How long the fade-out text effect lasts, in ticks.
		# 20 ticks = 1 second.
		# Default: 10
		"Text Fade-Out Time" = 10
		# The minimum amount of time in ticks that must pass after a biome title is displayed before
		# another can be displayed.
		# Useful for preventing the player from being spammed if they are traveling quickly.
		# 20 ticks = 1 second.
		# Default: 80
		"Text Cooldown Time" = 80
		# The text's default RGB color.
		# Default: "ffffff"
		"Default Text Color" = "ffffff"
		# The text's scale.
		# Default: 2.1
		"Text Size" = 2.1
		# If enabled, will render a shadow below the text making it easier to read.
		# Default: true
		"Display Text Shadow" = true
		# The text's vertical position on the screen.
		# If Horizontally Center Title is enabled, this number is relative to the center of the screen.
		# If Horizontally Center Title is disabled, this number is relative to the top of the screen.
		# Default: -33.0
		"Text Y Offset" = -33.0
		# The text's horizontal position on the screen.
		# If Horizontally Center Title is enabled, this number is relative to the center of the screen.
		# If Horizontally Center Title is disabled, this number is relative to the left side of the screen.
		# Default: 0.0
		"Text X Offset" = 0.0
		# Biomes that should not have any title displayed when the player enters them.
		# Example: "[minecraft:plains, minecraft:desert]"
		# Default: "[minecraft:the_end, minecraft:river, minecraft:frozen_river]"
		"Blacklisted Biomes" = "[minecraft:the_end, minecraft:river, minecraft:frozen_river]"
		# Traveler's Titles tracks a list of biomes the player most recently visited in order to
		# prevent the player from being spammed with titles when they move between the same few biomes.
		# This is the size of that list.
		# For example, if this value is 5, then your 5 most recent biomes will be saved.
		# Default: 5
		"Number of Most Recent Biomes Saved" = 5
		# Whether or not the biome text should be centered on the screen.
		# The Text X Offset and Text Y Offset options are relative to the center of the screen if this is enabled.
		# Default: true
		"Center Title" = true
		# Traveler's Titles tracks a list of biomes the player most recently visited in order to
		# prevent the player from being spammed with titles when they move between the same few biomes.
		# This option determines whether or not that list should be cleared every time
		# the player changes dimensions.
		# Default: true
		"Reset Biome Cache When Changing Dimensions" = true

	###########################################################################################################
	## Dimension Title settings.
	###########################################################################################################
	["Traveler's Titles"."Dimension Titles"]
		"Enable Dimension Titles" = true
		# How long the fade-in text effect lasts, in ticks.
		# 20 ticks = 1 second.
		# Default: 10
		"Text Fade-In Time" = 10
		# How long the text displays, in ticks.
		# 20 ticks = 1 second.
		# Default: 70
		"Text Display Time" = 70
		# How long the fade-out text effect lasts, in ticks.
		# 20 ticks = 1 second.
		# Default: 20
		"Text Fade-Out Time" = 20
		# The text's default RGB color.
		# Default: "ffffff"
		"Default Text Color" = "ffffff"
		# The text's scale.
		# Default: 3.0
		"Text Size" = 3.0
		# If enabled, will render a shadow below the text making it easier to read.
		# Default: true
		"Display Text Shadow" = true
		# The text's vertical position on the screen.
		# If Horizontally Center Title is enabled, this number is relative to the center of the screen.
		# If Horizontally Center Title is disabled, this number is relative to the top of the screen.
		# Default: -32.0
		"Text Y Offset" = -32.0
		# The text's horizontal position on the screen.
		# If Horizontally Center Title is enabled, this number is relative to the center of the screen.
		# If Horizontally Center Title is disabled, this number is relative to the left side of the screen.
		# Default: 0.0
		"Text X Offset" = 0.0
		# Dimensions that should not have any title displayed when the player enters them.
		# Example: "[minecraft:overworld, minecraft:the_nether]"
		# Default: "[]"
		"Blacklisted Dimensions" = "[]"
		# Whether or not the dimension text should be centered on the screen.
		# The Text X Offset and Text Y Offset options are relative to the center of the screen if this is enabled.
		# Default: true
		"Center Title" = true

