
[structures]

	#Ideally this configuration would be done via worldgen datapacks,
	#but due to the way we're working around the hardcodedness inherent to structures,
	#that doesn't seem to be working, so we're using forge configs for this for now.
	#The values for each of these are as follows:
	#* size -- the maximum iteration depth of the jigsaw placer for this structure.
	#       -- Total structure size can increase exponentially with this
	#       -- increasing this too high may cause dedicated servers to timeout and shut down
	#       -- (this is safe to increase to 50 on singleplayer worlds, though it still takes a while to generate)
	#* min_separation -- Minimum farapartness for generating instances of this structure
	#* max_separation -- Maximum farapartness for generating instances of this structure
	#       -- must be greater than min_separation or minecraft will crash
	#
	# The rest of these values should only be changed if worldgen datapacks are being used to significantly alter the structure:
	#* start_pool -- which structure template pool json the first piece in the structure uses
	#* snap_to_height_map -- if true, the first structure piece will be placed on the world's surface.
	#                     -- if false, start_y is used instead. Defaults to true
	#* start_y -- If snap_to_height_map is enabled, the first structure piece generates at this height.
	#          -- Otherwise, this is ignored. Defaults to 0
	#* enable_legacy_piece_intersactions -- if true, subtly alters the way the jigsaw placer determines
	#          -- whether two jigsaw pieces overlap. Defaults to false. Not recommended to turn on
	#
	#Changing anything in this config file requires a total shutdown and reboot of the minecraft client or server to take effect.
	[structures.desert_quarry]
		max_separation = 32
		start_pool = "workshopsofdoom:quarry/desert/start"
		size = 4
		min_seperation = 12

	[structures.plains_quarry]
		max_separation = 32
		start_pool = "workshopsofdoom:quarry/plains/start"
		size = 4
		min_seperation = 12

	[structures.mountain_mines]
		max_separation = 32
		start_pool = "workshopsofdoom:quarry/mountains/start"
		size = 10
		min_seperation = 12

	[structures.badlands_mines]
		max_separation = 32
		start_pool = "workshopsofdoom:quarry/badlands/start"
		size = 10
		min_seperation = 12

	[structures.workshop]
		max_separation = 32
		start_pool = "workshopsofdoom:workshop/start"
		size = 10
		min_seperation = 12

