
#Gui Configs
[gui]
	"Gui X" = 5
	"Gui Y" = 5
	#Textformatting codes for the display of the difficulty
	#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
	"Difficulty color" = "DARK_PURPLE"
	#Scaling of the difficulty text
	"Text Scale" = 1.0
	#Show the the difficulty text
	"Show Difficulty" = false
	#Relative location of the difficulty text in regards to the screen.
	#Allowed Values: TOPRIGHT, TOPLEFT, BOTTOMRIGHT, BOTTOMLEFT
	"Difficulty location" = "TOPLEFT"

