
#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for Repurposed Structures Villages 
# 1 for spawning in most chunks and 1001 for no spawn.
[Spawnrates]
	#Range: 1 ~ 1001
	badlandsVillageMaxChunkDistance = 84
	#Range: 1 ~ 1001
	birchVillageMaxChunkDistance = 97
	#Range: 1 ~ 1001
	darkForestVillageMaxChunkDistance = 87
	#Range: 1 ~ 1001
	jungleVillageMaxChunkDistance = 77
	#Range: 1 ~ 1001
	swampVillageMaxChunkDistance = 87
	#Range: 1 ~ 1001
	mountainsVillageMaxChunkDistance = 97
	#Range: 1 ~ 1001
	villageMushroomAverageChunkDistance = 44
	#Range: 1 ~ 1001
	giantTaigaVillageMaxChunkDistance = 87
	#Range: 1 ~ 1001
	oakVillageMaxChunkDistance = 97
	#Range: 1 ~ 1001
	crimsonVillageMaxChunkDistance = 60
	#Range: 1 ~ 1001
	warpedVillageMaxChunkDistance = 60

#-----------------------------------------------------------------------------------------
# Size of the village. This is how many pieces long a path can be from the start piece.
[Size]
	#Range: 1 ~ 30
	badlandsVillageSize = 4
	#Range: 1 ~ 30
	birchVillageSize = 4
	#Range: 1 ~ 30
	darkForestVillageSize = 4
	#Range: 1 ~ 30
	jungleVillageSize = 4
	#Range: 1 ~ 30
	swampVillageSize = 4
	#Range: 1 ~ 30
	mountainsVillageSize = 4
	#Range: 1 ~ 30
	mushroomVillageSize = 4
	#Range: 1 ~ 30
	giantTaigaVillageSize = 4
	#Range: 1 ~ 30
	oakVillageSize = 4
	#Range: 1 ~ 30
	crimsonVillageSize = 4
	#Range: 1 ~ 30
	warpedVillageSize = 4

